var g;g||=typeof Module !== 'undefined' ? Module : {};g.kc||(g.kc=0);g.kc++;
g.ENVIRONMENT_IS_PTHREAD||g.$ww||function(a){function b(n,q,w,p){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(k,x){k?p(k):w(x.buffer)});else{var u=new XMLHttpRequest;u.open("GET",n,!0);u.responseType="arraybuffer";u.onprogress=function(k){var x=q;k.total&&(x=k.total);if(k.loaded){u.vb?g.Gb[n].loaded=k.loaded:(u.vb=!0,g.Gb||(g.Gb={}),g.Gb[n]={loaded:k.loaded,total:x});var z=x=k=0,F;for(F in g.Gb){var R=g.Gb[F];
k+=R.total;x+=R.loaded;z++}k=Math.ceil(k*g.kc/z);g.setStatus&&g.setStatus(`Downloading data... (${x}/${k})`)}else!g.Gb&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+n);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)w(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(u,k,x){this.start=u;this.end=
k;this.audio=x}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.pd=u;u=a.files;for(var k=0;k<u.length;++k)n.prototype.vb[u[k].filename].onload();g.removeRunDependency("datafile_Test/Test.data")}g.FS_createPath("/","assets",!0,!0);n.prototype={vb:{},open:function(u,k){this.name=k;this.vb[k]=this;g.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.rc(this.pd.subarray(this.start,
this.end))},rc:function(u){g.FS_createDataFile(this.name,null,u,!0,!0,!0);g.removeRunDependency(`fp ${this.name}`);this.vb[this.name]=null}};for(var w=a.files,p=0;p<w.length;++p)(new n(w[p].start,w[p].end,w[p].audio||0)).open("GET",w[p].filename);g.addRunDependency("datafile_Test/Test.data");g.Rc||(g.Rc={});g.Rc["Test/Test.data"]={Id:!1};l?(q(l),l=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,m("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("Test.data",""):"Test.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?
g.getPreloadedPackage(e,f):null;l||b(e,f,function(n){h?(h(n),h=null):l=n},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/assets/Roboto.ttf",start:0,end:168260},{filename:"/assets/RobotoMono.ttf",start:168260,end:255496},{filename:"/assets/cube.obj",start:255496,end:256759},{filename:"/assets/teapot.obj",start:256759,end:797339},{filename:"/assets/text.txt",start:797339,end:797350}],remote_package_size:797350});
var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",ia,ja,ka;
if(ha){var fs=require("fs"),la=require("path");r=fa?la.dirname(r)+"/":__dirname+"/";ia=(a,b)=>{a=ma(a)?new URL(a):la.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};ka=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a};ja=(a,b,c,d=!0)=>{a=ma(a)?new URL(a):la.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);
process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof na||a.context instanceof na))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||fa)fa?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=r.startsWith("blob:")?"":r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1),ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=g.print||console.log.bind(console),m=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var pa;g.wasmBinary&&(pa=g.wasmBinary);
"object"!=typeof WebAssembly&&qa("no native wasm support detected");var ra,sa=!1,ta,t,v,ua,y,A,va,wa;function xa(){var a=ra.buffer;g.HEAP8=t=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAPU8=v=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=y=new Int32Array(a);g.HEAPU32=A=new Uint32Array(a);g.HEAPF32=va=new Float32Array(a);g.HEAPF64=wa=new Float64Array(a)}var ya=[],Aa=[],Ba=[],Ca=[];function Da(){var a=g.preRun.shift();ya.unshift(a)}var Ea=0,Fa=null,Ga=null;
function Ha(){Ea++;g.monitorRunDependencies?.(Ea)}function Ia(){Ea--;g.monitorRunDependencies?.(Ea);if(0==Ea&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga)){var a=Ga;Ga=null;a()}}function qa(a){g.onAbort?.(a);a="Aborted("+a+")";m(a);sa=!0;ta=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ja=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://"),Ka;Ka="Test.wasm";if(!Ja(Ka)){var La=Ka;Ka=g.locateFile?g.locateFile(La,r):r+La}
function Ma(a){if(a==Ka&&pa)return new Uint8Array(pa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}function Na(a){if(!pa&&(ea||fa)){if("function"==typeof fetch&&!ma(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ma(a));if(ja)return new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ma(a))}
function Oa(a,b,c){return Na(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{m(`failed to asynchronously prepare wasm: ${d}`);qa(d)})}function Pa(a,b){var c=Ka;pa||"function"!=typeof WebAssembly.instantiateStreaming||Ja(c)||ma(c)||ha||"function"!=typeof fetch?Oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){m(`wasm streaming compile failed: ${e}`);m("falling back to ArrayBuffer instantiation");return Oa(c,a,b)}))}
var B,C,Va={1036244:()=>{var a=a||"binary";if("utf8"!==a&&"binary"!==a)throw Error(`Invalid encoding type "${a}"`);var b;var c=Qa("Roboto.png",c||0);var d=Ra("Roboto.png").size,e=new Uint8Array(d);Sa(c,e,0,d,0);"utf8"===a?b=D(e,0):"binary"===a&&(b=e);Ta(c);a=new Blob([b],{type:"application/octet-stream"});b=document.createElement("a");document.body.appendChild(b);b.href=URL.createObjectURL(a);b.download="Roboto.png";b.click();document.body.removeChild(b);URL.revokeObjectURL(b.href)}};
function na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Wa=a=>{for(;0<a.length;)a.shift()(g)},Xa=g.noExitRuntime||!0,Ya=[],Za=0,$a=0;class ab{constructor(a){this.Nb=a;this.tb=a-24}}
var db=a=>{var b=$a;if(!b)return bb(0),0;var c=new ab(b);A[c.tb+16>>2]=b;var d=A[c.tb+4>>2];if(!d)return bb(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(cb(f,d,c.tb+16))return bb(f),b}bb(d);return b},eb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},fb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=eb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&
c&&(a+="/");return(b?"/":"")+a},gb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},hb=a=>{if("/"===a)return"/";a=fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},ib=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ha)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);
var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}qa("initRandomDevice")},jb=a=>(jb=ib())(a);function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:lb;if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=eb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var mb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&mb)return mb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
nb=[],ob=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},pb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&
63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function qb(a,b){var c=Array(ob(a)+1);a=pb(a,c,0,c.length);b&&(c.length=a);return c}var rb=[];function sb(a,b){rb[a]={input:[],output:[],Bb:b};tb(a,ub)}
var ub={open(a){var b=rb[a.node.rdev];if(!b)throw new E(43);a.tty=b;a.seekable=!1},close(a){a.tty.Bb.fsync(a.tty)},fsync(a){a.tty.Bb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Bb.Ic)throw new E(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Bb.Ic(a.tty)}catch(l){throw new E(29);}if(void 0===h&&0===e)throw new E(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Bb.qc)throw new E(60);try{for(var e=0;e<d;e++)a.tty.Bb.qc(a.tty,b[c+
e])}catch(f){throw new E(29);}d&&(a.node.timestamp=Date.now());return e}},vb={Ic(){a:{if(!nb.length){var a=null;if(ha){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}nb=qb(a,!0)}a=
nb.shift()}return a},qc(a,b){null===b||10===b?(oa(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(D(a.output,0)),a.output=[])},jd(){return{Cd:25856,Ed:5,Bd:191,Dd:35387,Ad:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},kd(){return 0},ld(){return[24,80]}},wb={qc(a,b){null===b||10===b?(m(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(m(D(a.output,0)),a.output=[])}},yb=a=>{a=65536*
Math.ceil(a/65536);var b=xb(65536,a);b?(v.fill(0,b,b+a),a=b):a=0;return a};function zb(a,b){var c=a.qb?a.qb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.qb,a.qb=new Uint8Array(b),0<a.ub&&a.qb.set(c.subarray(0,a.ub),0))}
var G={yb:null,Ab(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new E(63);G.yb||(G.yb={dir:{node:{xb:G.pb.xb,wb:G.pb.wb,lookup:G.pb.lookup,ac:G.pb.ac,rename:G.pb.rename,unlink:G.pb.unlink,rmdir:G.pb.rmdir,readdir:G.pb.readdir,symlink:G.pb.symlink},stream:{Db:G.rb.Db}},file:{node:{xb:G.pb.xb,wb:G.pb.wb},stream:{Db:G.rb.Db,read:G.rb.read,write:G.rb.write,zc:G.rb.zc,Pb:G.rb.Pb,bc:G.rb.bc}},link:{node:{xb:G.pb.xb,wb:G.pb.wb,readlink:G.pb.readlink},
stream:{}},Dc:{node:{xb:G.pb.xb,wb:G.pb.wb},stream:Ab}});c=Bb(a,b,c,d);H(c.mode)?(c.pb=G.yb.dir.node,c.rb=G.yb.dir.stream,c.qb={}):32768===(c.mode&61440)?(c.pb=G.yb.file.node,c.rb=G.yb.file.stream,c.ub=0,c.qb=null):40960===(c.mode&61440)?(c.pb=G.yb.link.node,c.rb=G.yb.link.stream):8192===(c.mode&61440)&&(c.pb=G.yb.Dc.node,c.rb=G.yb.Dc.stream);c.timestamp=Date.now();a&&(a.qb[b]=c,a.timestamp=c.timestamp);return c},Kd(a){return a.qb?a.qb.subarray?a.qb.subarray(0,a.ub):new Uint8Array(a.qb):new Uint8Array(0)},
pb:{xb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ub:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.bd=4096;b.blocks=Math.ceil(b.size/b.bd);return b},wb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ub!=b))if(0==
b)a.qb=null,a.ub=0;else{var c=a.qb;a.qb=new Uint8Array(b);c&&a.qb.set(c.subarray(0,Math.min(b,a.ub)));a.ub=b}},lookup(){throw Cb[44];},ac(a,b,c,d){return G.createNode(a,b,c,d)},rename(a,b,c){if(H(a.mode)){try{var d=Db(b,c)}catch(f){}if(d)for(var e in d.qb)throw new E(55);}delete a.parent.qb[a.name];a.parent.timestamp=Date.now();a.name=c;b.qb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.qb[b];a.timestamp=Date.now()},rmdir(a,b){var c=Db(a,b),d;for(d in c.qb)throw new E(55);delete a.qb[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.qb))b.push(c);return b},symlink(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new E(28);return a.link}},rb:{read(a,b,c,d,e){var f=a.node.qb;if(e>=a.node.ub)return 0;a=Math.min(a.node.ub-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===t.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();
if(b.subarray&&(!a.qb||a.qb.subarray)){if(f)return a.qb=b.subarray(c,c+d),a.ub=d;if(0===a.ub&&0===e)return a.qb=b.slice(c,c+d),a.ub=d;if(e+d<=a.ub)return a.qb.set(b.subarray(c,c+d),e),d}zb(a,e+d);if(a.qb.subarray&&b.subarray)a.qb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.qb[e+f]=b[c+f];a.ub=Math.max(a.ub,e+d);return d},Db(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ub);if(0>b)throw new E(28);return b},zc(a,b,c){zb(a.node,b+c);a.node.ub=Math.max(a.node.ub,b+c)},
Pb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new E(43);a=a.node.qb;if(e&2||a.buffer!==t.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=yb(b);if(!b)throw new E(48);t.set(a,b)}else c=!1,b=a.byteOffset;return{tb:b,Ac:c}},bc(a,b,c,d){G.rb.write(a,b,0,d,c,!1);return 0}}},Eb=(a,b,c)=>{var d=`al ${a}`;ja(a,e=>{b(new Uint8Array(e));d&&Ia(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ha(d)},Fb=g.preloadPlugins||[],Ib=(a,
b,c,d)=>{"undefined"!=typeof Gb&&Hb();var e=!1;Fb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Kb=(a,b,c,d,e,f,h,l,n,q)=>{function w(k){function x(z){q?.();l||Jb(a,b,z,d,e,n);f?.();Ia(u)}Ib(k,p,x,()=>{h?.();Ia(u)})||x(k)}var p=b?kb(fb(a+"/"+b)):a,u=`cp ${p}`;Ha(u);"string"==typeof c?Eb(c,w,h):w(c)},Lb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Mb=null,Nb={},Ob=[],Pb=1,Qb=null,lb="/",Rb=!0,E=class{constructor(a){this.name="ErrnoError";this.sb=a}},Cb={};
function I(a,b={}){a=kb(a);if(!a)return{path:"",node:null};b=Object.assign({Hc:!0,sc:0},b);if(8<b.sc)throw new E(32);a=a.split("/").filter(h=>!!h);for(var c=Mb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Db(c,a[e]);d=fb(d+"/"+a[e]);c.Hb&&(!f||f&&b.Hc)&&(c=c.Hb.root);if(!f||b.Ob)for(f=0;40960===(c.mode&61440);)if(c=Sb(d),d=kb(gb(d),c),c=I(d,{sc:b.sc+1}).node,40<f++)throw new E(32);}return{path:d,node:c}}
function Tb(a){for(var b;;){if(a===a.parent)return a=a.Ab.Oc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Ub(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Qb.length}function Vb(a){var b=Ub(a.parent.id,a.name);if(Qb[b]===a)Qb[b]=a.Ib;else for(b=Qb[b];b;){if(b.Ib===a){b.Ib=a.Ib;break}b=b.Ib}}
function Db(a,b){var c=H(a.mode)?(c=Wb(a,"x"))?c:a.pb.lookup?0:2:54;if(c)throw new E(c);for(c=Qb[Ub(a.id,b)];c;c=c.Ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.pb.lookup(a,b)}function Bb(a,b,c,d){a=new Xb(a,b,c,d);b=Ub(a.parent.id,a.name);a.Ib=Qb[b];return Qb[b]=a}function H(a){return 16384===(a&61440)}function Yb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Wb(a,b){if(Rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Zb(a,b){try{return Db(a,b),20}catch(c){}return Wb(a,"wx")}function $b(a,b,c){try{var d=Db(a,b)}catch(e){return e.sb}if(a=Wb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(d===d.parent||Tb(d)===lb)return 10}else if(H(d.mode))return 31;return 0}function ac(){for(var a=0;4096>=a;a++)if(!Ob[a])return a;throw new E(33);}
function J(a){a=Ob[a];if(!a)throw new E(8);return a}function bc(a,b=-1){cc||(cc=function(){this.vb={}},cc.prototype={},Object.defineProperties(cc.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.vb.flags},set(c){this.vb.flags=c}},position:{get(){return this.vb.position},set(c){this.vb.position=c}}}));a=Object.assign(new cc,a);-1==b&&(b=ac());a.fd=b;return Ob[b]=a}var Ab={open(a){a.rb=Nb[a.node.rdev].rb;a.rb.open?.(a)},Db(){throw new E(70);}};
function tb(a,b){Nb[a]={rb:b}}function dc(a,b){var c="/"===b;if(c&&Mb)throw new E(10);if(!c&&b){var d=I(b,{Hc:!1});b=d.path;d=d.node;if(d.Hb)throw new E(10);if(!H(d.mode))throw new E(54);}b={type:a,Rd:{},Oc:b,od:[]};a=a.Ab(b);a.Ab=b;b.root=a;c?Mb=a:d&&(d.Hb=b,d.Ab&&d.Ab.od.push(b))}function ec(a,b,c){var d=I(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new E(28);var e=Zb(d,a);if(e)throw new E(e);if(!d.pb.ac)throw new E(63);return d.pb.ac(d,a,b,c)}
function K(a,b){return ec(a,(void 0!==b?b:511)&1023|16384,0)}function fc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return ec(a,b|8192,c)}function gc(a,b){if(!kb(a))throw new E(44);var c=I(b,{parent:!0}).node;if(!c)throw new E(44);b=hb(b);var d=Zb(c,b);if(d)throw new E(d);if(!c.pb.symlink)throw new E(63);c.pb.symlink(c,b,a)}function hc(a){var b=I(a,{parent:!0}).node;a=hb(a);var c=Db(b,a),d=$b(b,a,!0);if(d)throw new E(d);if(!b.pb.rmdir)throw new E(63);if(c.Hb)throw new E(10);b.pb.rmdir(b,a);Vb(c)}
function ic(a){var b=I(a,{parent:!0}).node;if(!b)throw new E(44);a=hb(a);var c=Db(b,a),d=$b(b,a,!1);if(d)throw new E(d);if(!b.pb.unlink)throw new E(63);if(c.Hb)throw new E(10);b.pb.unlink(b,a);Vb(c)}function Sb(a){a=I(a).node;if(!a)throw new E(44);if(!a.pb.readlink)throw new E(28);return kb(Tb(a.parent),a.pb.readlink(a))}function Ra(a,b){a=I(a,{Ob:!b}).node;if(!a)throw new E(44);if(!a.pb.xb)throw new E(63);return a.pb.xb(a)}function jc(a){return Ra(a,!0)}
function kc(a,b){a="string"==typeof a?I(a,{Ob:!0}).node:a;if(!a.pb.wb)throw new E(63);a.pb.wb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Qa(a,b,c){if(""===a)throw new E(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=fb(a);try{e=I(a,{Ob:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new E(20);}else e=ec(a,c,0),d=!0;if(!e)throw new E(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!H(e.mode))throw new E(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:H(e.mode)&&("r"!==Yb(b)||b&512)?31:Wb(e,Yb(b)):44))throw new E(c);if(b&512&&!d){c=e;c="string"==typeof c?I(c,{Ob:!0}).node:c;if(!c.pb.wb)throw new E(63);if(H(c.mode))throw new E(31);if(32768!==(c.mode&61440))throw new E(28);if(d=Wb(c,"w"))throw new E(d);c.pb.wb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=bc({node:e,path:Tb(e),flags:b,seekable:!0,position:0,rb:e.rb,vd:[],error:!1});e.rb.open&&e.rb.open(e);!g.logReadFiles||b&1||(lc||={},a in lc||(lc[a]=1));return e}
function Ta(a){if(null===a.fd)throw new E(8);a.nc&&(a.nc=null);try{a.rb.close&&a.rb.close(a)}catch(b){throw b;}finally{Ob[a.fd]=null}a.fd=null}function mc(a,b,c){if(null===a.fd)throw new E(8);if(!a.seekable||!a.rb.Db)throw new E(70);if(0!=c&&1!=c&&2!=c)throw new E(28);a.position=a.rb.Db(a,b,c);a.vd=[]}
function Sa(a,b,c,d,e){if(0>d||0>e)throw new E(28);if(null===a.fd)throw new E(8);if(1===(a.flags&2097155))throw new E(8);if(H(a.node.mode))throw new E(31);if(!a.rb.read)throw new E(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new E(70);b=a.rb.read(a,b,c,d,e);f||(a.position+=b);return b}
function nc(a,b,c,d,e,f){if(0>d||0>e)throw new E(28);if(null===a.fd)throw new E(8);if(0===(a.flags&2097155))throw new E(8);if(H(a.node.mode))throw new E(31);if(!a.rb.write)throw new E(28);a.seekable&&a.flags&1024&&mc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new E(70);b=a.rb.write(a,b,c,d,e,f);h||(a.position+=b);return b}var oc;
function pc(a,b){a="string"==typeof a?a:Tb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=fb(a+"/"+c);try{K(d)}catch(e){}a=d}}return d}function qc(a,b,c,d){a=fb(("string"==typeof a?a:Tb(a))+"/"+b);c=Lb(c,d);return ec(a,(void 0!==c?c:438)&4095|32768,0)}
function Jb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Tb(a),h=b?fb(a+"/"+b):a);a=Lb(d,e);h=ec(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}kc(h,a|146);b=Qa(h,577);nc(b,c,0,c.length,0,f);Ta(b);kc(h,a)}}
function rc(a,b,c,d){a=fb(("string"==typeof a?a:Tb(a))+"/"+b);b=Lb(!!c,!!d);rc.Lc||(rc.Lc=64);var e=rc.Lc++<<8|0;tb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,l,n){for(var q=0,w=0;w<n;w++){try{var p=c()}catch(u){throw new E(29);}if(void 0===p&&0===q)throw new E(6);if(null===p||void 0===p)break;q++;h[l+w]=p}q&&(f.node.timestamp=Date.now());return q},write(f,h,l,n){for(var q=0;q<n;q++)try{d(h[l+q])}catch(w){throw new E(29);}n&&(f.node.timestamp=Date.now());return q}});return fc(a,
b,e)}function sc(a){if(!(a.md||a.nd||a.link||a.qb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.qb=qb(ia(a.url),!0),a.ub=a.qb.length}catch(b){throw new E(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function tc(a,b,c,d,e){function f(){this.pc=!1;this.vb=[]}function h(p,u,k,x,z){p=p.node.qb;if(z>=p.length)return 0;x=Math.min(p.length-z,x);if(p.slice)for(var F=0;F<x;F++)u[k+F]=p[z+F];else for(F=0;F<x;F++)u[k+F]=p.get(z+F);return x}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var u=p%this.chunkSize;return this.Jc(p/this.chunkSize|0)[u]}};f.prototype.rc=function(p){this.Jc=p};f.prototype.Bc=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||
304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var u=Number(p.getResponseHeader("Content-length")),k,x=(k=p.getResponseHeader("Accept-Ranges"))&&"bytes"===k;p=(k=p.getResponseHeader("Content-Encoding"))&&"gzip"===k;var z=1048576;x||(z=u);var F=this;F.rc(R=>{var Ua=R*z,za=(R+1)*z-1;za=Math.min(za,u-1);if("undefined"==typeof F.vb[R]){var te=F.vb;if(Ua>za)throw Error("invalid range ("+Ua+", "+za+") or no bytes requested!");if(za>u-1)throw Error("only "+u+" bytes available! programmer error!");
var Q=new XMLHttpRequest;Q.open("GET",c,!1);u!==z&&Q.setRequestHeader("Range","bytes="+Ua+"-"+za);Q.responseType="arraybuffer";Q.overrideMimeType&&Q.overrideMimeType("text/plain; charset=x-user-defined");Q.send(null);if(!(200<=Q.status&&300>Q.status||304===Q.status))throw Error("Couldn't load "+c+". Status: "+Q.status);Ua=void 0!==Q.response?new Uint8Array(Q.response||[]):qb(Q.responseText||"",!0);te[R]=Ua}if("undefined"==typeof F.vb[R])throw Error("doXHR failed!");return F.vb[R]});if(p||!u)z=u=1,
z=u=this.Jc(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.ad=u;this.$c=z;this.pc=!0};if("undefined"!=typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.pc||this.Bc();return this.ad}},chunkSize:{get:function(){this.pc||this.Bc();return this.$c}}});var n=void 0}else n=c,l=void 0;var q=
qc(a,b,d,e);l?q.qb=l:n&&(q.qb=null,q.url=n);Object.defineProperties(q,{ub:{get:function(){return this.qb.length}}});var w={};Object.keys(q.rb).forEach(p=>{var u=q.rb[p];w[p]=function(){sc(q);return u.apply(null,arguments)}});w.read=(p,u,k,x,z)=>{sc(q);return h(p,u,k,x,z)};w.Pb=(p,u,k)=>{sc(q);var x=yb(u);if(!x)throw new E(48);h(p,t,x,u,k);return{tb:x,Ac:!0}};q.rb=w;return q}var L={},cc,lc;
function uc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?lb:J(a).path;if(0==b.length){if(!c)throw new E(44);return a}return fb(a+"/"+b)}
function vc(a,b,c){a=a(b);y[c>>2]=a.dev;y[c+4>>2]=a.mode;A[c+8>>2]=a.nlink;y[c+12>>2]=a.uid;y[c+16>>2]=a.gid;y[c+20>>2]=a.rdev;C=[a.size>>>0,(B=a.size,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[c+24>>2]=C[0];y[c+28>>2]=C[1];y[c+32>>2]=4096;y[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();C=[Math.floor(b/1E3)>>>0,(B=Math.floor(b/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>
0))/4294967296)>>>0:0)];y[c+40>>2]=C[0];y[c+44>>2]=C[1];A[c+48>>2]=b%1E3*1E3;C=[Math.floor(d/1E3)>>>0,(B=Math.floor(d/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[c+56>>2]=C[0];y[c+60>>2]=C[1];A[c+64>>2]=d%1E3*1E3;C=[Math.floor(e/1E3)>>>0,(B=Math.floor(e/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[c+72>>2]=C[0];y[c+76>>2]=C[1];A[c+80>>2]=e%1E3*1E3;C=[a.ino>>>0,(B=a.ino,1<=+Math.abs(B)?
0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[c+88>>2]=C[0];y[c+92>>2]=C[1];return 0}var wc=void 0;function xc(){var a=y[+wc>>2];wc+=4;return a}
var yc=a=>0===a%4&&(0!==a%100||0===a%400),zc=[0,31,60,91,121,152,182,213,244,274,305,335],Ac=[0,31,59,90,120,151,181,212,243,273,304,334],Bc=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN,Dc=a=>{var b=ob(a)+1,c=Cc(b);c&&pb(a,v,c,b);return c},Ec=[],Pc=(a,b)=>{Fc=a;Gc=b;if(Hc)if(Ic||=!0,0==a)Jc=function(){var d=Math.max(0,Kc+b-Lc())|0;setTimeout(Mc,d)};else if(1==a)Jc=function(){Nc(Mc)};else if(2==a){if("undefined"==typeof Oc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",
d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Oc=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Oc=setImmediate;Jc=function(){Oc(Mc)}}},Lc;Lc=()=>performance.now();
var Yc=(a,b,c,d,e)=>{!Hc||qa("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Hc=a;Qc=d;var f=Rc;Ic=!1;Mc=function(){if(!sa)if(0<Sc.length){var h=Sc.shift();h.Jd(h.xd);if(Tc){var l=Tc,n=0==l%1?l-1:Math.floor(l);Tc=h.Fd?n:(8*l+(n+.5))/9}g.setStatus&&(h=g.statusMessage||"Please wait...",l=Tc,n=Uc.Hd,l?l<n?g.setStatus(h+" ("+(n-l)+"/"+n+")"):g.setStatus(h):g.setStatus(""));
f<Rc||setTimeout(Mc,0)}else if(!(f<Rc))if(Vc=Vc+1|0,1==Fc&&1<Gc&&0!=Vc%Gc)Jc();else{0==Fc&&(Kc=Lc());if(M)for(h=M.Kb,M.Kb=M.Qb,M.Qb=h,h=M.Cb,M.Cb=M.cc,M.cc=h,h=0;21>=h;++h)M.Cb[h]=0;if(!(sa||g.preMainLoop&&!1===g.preMainLoop())){if(!sa)try{a(),Wc()}catch(q){Xc(q)}g.postMainLoop?.()}f<Rc||("object"==typeof SDL&&SDL.audio?.Sd?.(),Jc())}};e||(b&&0<b?Pc(0,1E3/b):Pc(1,1),Jc());if(c)throw"unwind";},Xc=a=>{a instanceof na||"unwind"==a||da(1,a)},Zc=a=>{ta=a;Xa||(g.onExit?.(a),sa=!0);da(a,new na(a))},$c=a=>
{ta=a;Zc(a)},Wc=()=>{if(!Xa)try{var a=ta;ta=a;Zc(a)}catch(b){Xc(b)}},ad=a=>{setTimeout(()=>{if(!sa)try{a(),Wc()}catch(b){Xc(b)}},1E4)},Ic=!1,Jc=null,Rc=0,Hc=null,Qc=0,Fc=0,Gc=0,Vc=0,Sc=[];function bd(){Jc=null;Rc++}var Uc={},Kc,Mc,Tc,cd=!1,dd=!1,ed=[];
function Hb(){function a(){dd=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!fd){fd=!0;Fb.push({canHandle:function(c){return!g.Qd&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=new Blob([c],{type:gd(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:gd(d)}));var l=URL.createObjectURL(h),n=new Image;n.onload=()=>{n.complete||qa(`Image ${d} could not be decoded`);
var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(l);e?.(c)};n.onerror=()=>{m(`Image ${l} could not be decoded`);f?.()};n.src=l}});Fb.push({canHandle:function(c){return!g.Pd&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){h||(h=!0,e?.(c))}var h=!1,l=URL.createObjectURL(new Blob([c],{type:gd(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!h){m(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var q="",w=0,p=0,u=0;u<c.length;u++)for(w=w<<8|c[u],p+=8;6<=p;){var k=w>>p-6&63;p-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[k]}2==p?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],q+="=="):4==p&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],q+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+q;f(n)}};n.src=l;ad(()=>{f(n)})}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",
c=>{!dd&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function hd(a,b,c,d){if(b&&g.Lb&&a==g.canvas)return g.Lb;var e;if(b){var f={antialias:!1,alpha:!1,Mc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof jd&&(e=kd(a,f)))var l=ld[e].Sb}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof N||qa("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Lb=l,b&&(M=ld[e],g.Lb=N=M?.Sb),g.Vd=b,ed.forEach(n=>n()),Hb());return l}var md=!1,nd=void 0,O=void 0;
function od(a,b){function c(){cd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=pd,nd&&d.requestPointerLock(),cd=!0,O?qd():rd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),O?sd():rd(d));g.onFullScreen?.(cd);g.onFullscreen?.(cd)}nd=a;O=b;"undefined"==typeof nd&&(nd=!0);"undefined"==typeof O&&(O=!1);var d=g.canvas;md||(md=
!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?
()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function pd(){if(!cd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var td=0;function Nc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===td)td=b+1E3/60;else for(;b+2>=td;)td+=1E3/60;setTimeout(a,Math.max(td-b,0))}}
function gd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ud=0,vd=0,wd=0,xd=0;function yd(a,b){var c=g.canvas.getBoundingClientRect(),d=g.canvas.height;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=g.canvas.width/c.width;b*=d/c.height;return{x:a,y:b}}
function zd(a,b){const {x:c,y:d}=yd(a,b);wd=c-ud;xd=d-vd;ud=c;vd=d}function Ad(a){dd?("mousemove"!=a.type&&"mozMovementX"in a?wd=xd=0:(wd=a.movementX||a.mozMovementX||a.webkitMovementX||0,xd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ud=SDL.Md+wd,vd=SDL.Nd+xd):(ud+=wd,vd+=xd)):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.Ud,void 0!==a&&yd(a.pageX,a.pageY)):zd(a.pageX,a.pageY)}var Bd=[];
function Cd(){var a=g.canvas;Bd.forEach(b=>b(a.width,a.height))}function Dd(a,b,c){rd(g.canvas,a,b);c||Cd()}function qd(){"undefined"!=typeof SDL&&(y[SDL.screen>>2]=A[SDL.screen>>2]|8388608);rd(g.canvas);Cd()}function sd(){"undefined"!=typeof SDL&&(y[SDL.screen>>2]=A[SDL.screen>>2]&-8388609);rd(g.canvas);Cd()}
function rd(a,b,c){b&&c?(a.yc=b,a.oc=c):(b=a.yc,c=a.oc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}O?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Gb={},Oc,fd,Ed=[],Fd,P=a=>{var b=Ed[a];b||(a>=Ed.length&&(Ed.length=a+1),Ed[a]=b=Fd.get(a));return b},Gd={},Id=()=>{if(!Hd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gd)void 0===Gd[b]?delete a[b]:a[b]=Gd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hd=c}return Hd},Hd,Jd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");
b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},Kd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ld=a=>{var b=a.getExtension("WEBGL_draw_buffers");
b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))};
function Md(a){var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))}var Nd=1,Od=[],S=[],T=[],Pd=[],ld=[],Qd=[],Rd=[1,1,2,2,4,4,4,2,3,4,8];function Sd(a){Td||=a}
var Ud=a=>{for(var b=Nd++,c=a.length;c<b;c++)a[c]=null;return b},kd=(a,b)=>{a.vb||(a.vb=a.getContext,a.getContext=function(d,e){e=a.vb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Mc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Vd(c,b):0},Vd=(a,b)=>{var c=Ud(ld),d={handle:c,attributes:b,version:b.Mc,Sb:a};a.canvas&&(a.canvas.wd=d);ld[c]=d;("undefined"==typeof b.ed||b.ed)&&Wd(d);d.Nc=d.Sb.getParameter(34921);d.Tb=[];for(a=0;a<d.Nc;a++)d.Tb[a]={enabled:!1,
fc:!1,size:0,type:0,Qc:0,vc:0,tb:0,Xc:null};d.Cb=[];d.cc=[];d.Cb.length=d.cc.length=22;d.Kb=[];d.Qb=[];d.Kb.length=d.Qb.length=22;d.Jb=[];d.Jb.length=22;for(a=0;21>=a;++a){d.Jb[a]=null;d.Cb[a]=d.cc[a]=0;d.Kb[a]=[];d.Qb[a]=[];b=d.Kb[a];var e=d.Qb[a];b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},Wd=a=>{a||=M;if(!a.gd){a.gd=!0;var b=a.Sb;Jd(b);Kd(b);Ld(b);b.Gd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ld=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Gc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Gc)b.Gc=b.getExtension("EXT_disjoint_timer_query");b.Od=b.getExtension("WEBGL_multi_draw");Md(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},jd={},Td,M,Xd,Yd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=N[c](),h=f&&Ud(d);f?(f.name=h,d[h]=f):Sd(1282);y[b+4*e>>2]=h}},Zd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),$d=a=>{var b=N.dd;if(b){var c=b.Rb[a];"number"==typeof c&&(b.Rb[a]=c=
N.getUniformLocation(b,b.Vc[a]+(0<c?`[${c}]`:"")));return c}Sd(1282)},ae=[];function be(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.Xb=!1;this.Uc=this.Tc=0;this.width=b;this.height=c;this.mc=d;this.lc=e;this.uc=b;this.tc=c;this.title=f;this.attributes=Object.assign({},ce);this.buttons=0;this.keys=[];this.ic=[];this.qd=0;this.title=null;this.Cc=this.Kc=this.jc=this.Sc=this.Vb=this.hc=this.Pc=this.Yc=this.Wb=this.Zc=0}
var U=null,de=null,V=null,ee=null,ce=null,fe=null,ge={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},he=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;
case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;
case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;
case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;
case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;default:return-1}},
ie=()=>{var a=U,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},je=a=>{U&&U.Cc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||P(U.Cc)(U.id,a))},ke=(a,b)=>{if(U){var c=he(a);if(-1!=c){var d=b&&U.keys[c];U.keys[c]=b;U.ic[a]=b;U.Kc&&(d&&(b=2),P(U.Kc)(U.id,c,a,b,ie()))}}},me=()=>{le()},ne=()=>{le()},oe=a=>{ke(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},pe=a=>{ke(a.keyCode,0)},qe=()=>{if(U)for(var a=0;a<U.ic.length;++a)U.ic[a]&&
ke(a,0)},re=a=>{if(U){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(fe===c.identifier){zd(c.pageX,c.pageY);b=!0;break}if(!b)return}else Ad(a);a.target==g.canvas&&U.hc&&U.hc&&P(U.hc)(U.id,ud,vd)}},se=a=>{U&&a.target==g.canvas&&U.Vb&&P(U.Vb)(U.id,1)},ue=a=>{U&&a.target==g.canvas&&U.Vb&&P(U.Vb)(U.id,0)},ve=(a,b)=>{if(U&&a.target==g.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();var d=!1;if(null===fe&&"touchstart"===
a.type&&0<a.targetTouches.length)d=a.targetTouches[0],fe=d.identifier,zd(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(fe===e.identifier){fe=null;d=!0;break}if(!d)return}else Ad(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){U.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else U.buttons&=~(1<<c);U.Pc&&P(U.Pc)(U.id,c,b,ie())}},we=a=>{U&&ve(a,1)},xe=a=>{U&&ve(a,0)},ye=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=
a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(U&&U.Sc&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;P(U.Sc)(U.id,b,c);a.preventDefault()}},ze=(a,b,c,d)=>{if(U){var e=!1;document.fullscreen||document.fullScreen||document.mozFullScreen||
document.webkitIsFullScreen?U.Xb||(e=a!=screen.width||b!=screen.height,U.Tc=U.x,U.Uc=U.y,U.uc=U.width,U.tc=U.height,U.x=U.y=0,U.width=screen.width,U.height=screen.height,U.Xb=!0):1==U.Xb&&(e=a!=U.uc||b!=U.tc,U.x=U.Tc,U.y=U.Uc,U.width=U.uc,U.height=U.tc,U.Xb=!1);if(e)Dd(U.width,U.height);else if(U.width!=a||U.height!=b||U.mc!=c||U.lc!=d)U.width=a,U.height=b,U.mc=c,U.lc=d,U&&U.Zc&&P(U.Zc)(U.id,U.width,U.height),U&&U.Wb&&P(U.Wb)(U.id,U.mc,U.lc)}},Ae={},Be=[],Ce=null,le=()=>{if(Vc!==Ce||!Vc){Be=navigator.getGamepads?
navigator.getGamepads():navigator.webkitGetGamepads||[];Ce=Vc;for(var a=0;a<Be.length;++a){var b=Be[a];if(b){Ae[a]||(oa("glfw joystick connected:",a),Ae[a]={id:Dc(b.id),zd:b.buttons.length,yd:b.axes.length,buttons:Cc(b.buttons.length),axes:Cc(4*b.axes.length)});for(var c=Ae[a],d=0;d<b.buttons.length;++d)t[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)va[c.axes+4*d>>2]=b.axes[d]}else Ae[a]&&(oa("glfw joystick disconnected",a),De(Ae[a].id),De(Ae[a].buttons),De(Ae[a].axes),delete Ae[a])}}},
Ee=a=>{function b(l){var n="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=p=>{if(2!=q.readyState)++f,oa("failed to read dropped file: "+l.name+": "+q.error);else{var u=new Uint8Array(p.target.result);p={};p.flags=p.flags||577;var k=Qa(n,p.flags,p.mode);if("string"==typeof u){var x=new Uint8Array(ob(u)+1);u=pb(u,x,0,x.length);nc(k,x,0,u,void 0,p.cd)}else if(ArrayBuffer.isView(u))nc(k,u,0,u.byteLength,void 0,p.cd);else throw Error("Unsupported data type");Ta(k);if(++f===
e){P(U.jc)(U.id,e,c);for(p=0;p<d.length;++p)De(d[p]);De(c)}}};q.readAsArrayBuffer(l);var w=Dc(n);d.push(w);A[c+4*h>>2]=w}if(U&&U.jc&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Cc(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;pc("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}},Fe=a=>{if(U&&U.jc)return a.preventDefault(),!1};
function Ge(a,b){function c(){cd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=pd,nd&&d.requestPointerLock(),cd=!0,O?qd():(rd(d),Cd())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),O?sd():(rd(d),Cd()));if(g.onFullScreen)g.onFullScreen(cd);if(g.onFullscreen)g.onFullscreen(cd)}nd=a;O=b;"undefined"==typeof nd&&(nd=!0);"undefined"==
typeof O&&(O=!1);var d=g.canvas;md||(md=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function He(a,b,c){var d=U&&0<U.attributes[139276]?de:1;b&&c?(a.yc=b,a.oc=c):(b=a.yc,c=a.oc);var e=b,f=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(e/f<g.forcedAspectRatio?e=Math.round(f*g.forcedAspectRatio):f=Math.round(e/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/e,screen.height/
f);e=Math.round(e*h);f=Math.round(f*h)}O&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}
function Ie(a,b){var c=g.canvas.getBoundingClientRect(),d=g.canvas.clientHeight;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=g.canvas.clientWidth/c.width;b*=d/c.height;return{x:a,y:b}}function Je(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}function Ke(){const a=g.canvas;rd(a,a.clientWidth,a.clientHeight);Cd()}
function Le(){de=Je();U&&U.Yc&&P(U.Yc)(U.id,de,de);Ke()}
var Me=[31,29,31,30,31,30,31,31,30,31,30,31],Ne=[31,28,31,30,31,30,31,31,30,31,30,31],Oe=(a,b,c,d)=>{function e(k,x,z){for(k="number"==typeof k?k.toString():k||"";k.length<x;)k=z[0]+k;return k}function f(k,x){return e(k,x,"0")}function h(k,x){function z(R){return 0>R?-1:0<R?1:0}var F;0===(F=z(k.getFullYear()-x.getFullYear()))&&0===(F=z(k.getMonth()-x.getMonth()))&&(F=z(k.getDate()-x.getDate()));return F}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;
case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function n(k){var x=k.Eb;for(k=new Date((new Date(k.Fb+1900,0,1)).getTime());0<x;){var z=k.getMonth(),F=(yc(k.getFullYear())?Me:Ne)[z];if(x>F-k.getDate())x-=F-k.getDate()+1,k.setDate(1),11>z?k.setMonth(z+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+
x);break}}z=new Date(k.getFullYear()+1,0,4);x=l(new Date(k.getFullYear(),0,4));z=l(z);return 0>=h(x,k)?0>=h(z,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=A[d+40>>2];d={td:y[d>>2],sd:y[d+4>>2],dc:y[d+8>>2],wc:y[d+12>>2],ec:y[d+16>>2],Fb:y[d+20>>2],zb:y[d+24>>2],Eb:y[d+28>>2],Td:y[d+32>>2],rd:y[d+36>>2],ud:q?q?D(v,q):"":""};c=c?D(v,c):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S",
"%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var w in q)c=c.replace(new RegExp(w,"g"),q[w]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),u="January February March April May June July August September October November December".split(" ");q={"%a":k=>p[k.zb].substring(0,3),"%A":k=>p[k.zb],"%b":k=>
u[k.ec].substring(0,3),"%B":k=>u[k.ec],"%C":k=>f((k.Fb+1900)/100|0,2),"%d":k=>f(k.wc,2),"%e":k=>e(k.wc,2," "),"%g":k=>n(k).toString().substring(2),"%G":n,"%H":k=>f(k.dc,2),"%I":k=>{k=k.dc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var x=0,z=0;z<=k.ec-1;x+=(yc(k.Fb+1900)?Me:Ne)[z++]);return f(k.wc+x,3)},"%m":k=>f(k.ec+1,2),"%M":k=>f(k.sd,2),"%n":()=>"\n","%p":k=>0<=k.dc&&12>k.dc?"AM":"PM","%S":k=>f(k.td,2),"%t":()=>"\t","%u":k=>k.zb||7,"%U":k=>f(Math.floor((k.Eb+7-k.zb)/7),2),"%V":k=>{var x=
Math.floor((k.Eb+7-(k.zb+6)%7)/7);2>=(k.zb+371-k.Eb-2)%7&&x++;if(x)53==x&&(z=(k.zb+371-k.Eb)%7,4==z||3==z&&yc(k.Fb)||(x=1));else{x=52;var z=(k.zb+7-k.Eb-1)%7;(4==z||5==z&&yc(k.Fb%400-1))&&x++}return f(x,2)},"%w":k=>k.zb,"%W":k=>f(Math.floor((k.Eb+7-(k.zb+6)%7)/7),2),"%y":k=>(k.Fb+1900).toString().substring(2),"%Y":k=>k.Fb+1900,"%z":k=>{k=k.rd;var x=0<=k;k=Math.abs(k)/60;return(x?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.ud,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(w in q)c.includes(w)&&
(c=c.replace(new RegExp(w,"g"),q[w](d)));c=c.replace(/\0\0/g,"%");w=qb(c,!1);if(w.length>b)return 0;t.set(w,a);return w.length-1};function Xb(a,b,c,d){a||=this;this.parent=a;this.Ab=a.Ab;this.Hb=null;this.id=Pb++;this.name=b;this.mode=c;this.pb={};this.rb={};this.rdev=d}
Object.defineProperties(Xb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},nd:{get:function(){return H(this.mode)}},md:{get:function(){return 8192===(this.mode&61440)}}});[44].forEach(a=>{Cb[a]=new E(a);Cb[a].stack="<generic error, no stack>"});Qb=Array(4096);dc(G,"/");K("/tmp");K("/home");K("/home/web_user");
(function(){K("/dev");tb(259,{read:()=>0,write:(d,e,f,h)=>h});fc("/dev/null",259);sb(1280,vb);sb(1536,wb);fc("/dev/tty",1280);fc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=jb(a).byteLength);return a[--b]};rc("/dev","random",c);rc("/dev","urandom",c);K("/dev/shm");K("/dev/shm/tmp")})();
(function(){K("/proc");var a=K("/proc/self");K("/proc/self/fd");dc({Ab(){var b=Bb(a,"fd",16895,73);b.pb={lookup(c,d){var e=J(+d);c={parent:null,Ab:{Oc:"fake"},pb:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=pc;g.FS_createDataFile=Jb;g.FS_createPreloadedFile=Kb;g.FS_unlink=ic;g.FS_createLazyFile=tc;g.FS_createDevice=rc;g.requestFullscreen=od;g.requestAnimationFrame=Nc;g.setCanvasSize=Dd;g.pauseMainLoop=bd;
g.resumeMainLoop=function(){Rc++;var a=Fc,b=Gc,c=Hc;Hc=null;Yc(c,0,!1,Qc,!0);Pc(a,b);Jc()};g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=hd;for(var N,Pe=new Float32Array(288),Qe=0;288>Qe;++Qe)ae[Qe]=Pe.subarray(0,Qe+1);
var mf={q:a=>{a=new ab(a);0==t[a.tb+12>>0]&&(t[a.tb+12>>0]=1,Za--);t[a.tb+13>>0]=0;Ya.push(a);Re(a.Nb);if(Se(A[a.tb+4>>2]))a=A[a.Nb>>2];else{var b=A[a.tb+16>>2];a=0!==b?b:a.Nb}return a},s:()=>{W(0,0);var a=Ya.pop();Te(a.Nb);$a=0},b:()=>db([]),m:a=>db([a]),L:(a,b,c,d)=>db([a,b,c,d]),ra:()=>{var a=Ya.pop();a||qa("no exception to throw");var b=a.Nb;0==t[a.tb+13>>0]&&(Ya.push(a),t[a.tb+13>>0]=1,t[a.tb+12>>0]=0,Za++);$a=b;throw $a;},a:(a,b,c)=>{var d=new ab(a);A[d.tb+16>>2]=0;A[d.tb+4>>2]=b;A[d.tb+8>>
2]=c;$a=a;Za++;throw $a;},d:a=>{$a||=a;throw $a;},na:function(a){try{a=a?D(v,a):"";var b=I(a,{Ob:!0});if(null===b.node)throw new E(44);if(!H(b.node.mode))throw new E(54);var c=Wb(b.node,"x");if(c)throw new E(c);lb=b.path;return 0}catch(d){if("undefined"==typeof L||"ErrnoError"!==d.name)throw d;return-d.sb}},A:function(a,b,c){wc=c;try{var d=J(a);switch(b){case 0:var e=xc();if(0>e)break;for(;Ob[e];)e++;return bc(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=xc(),d.flags|=e,0;
case 12:return e=xc(),ua[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof L||"ErrnoError"!==f.name)throw f;return-f.sb}},ja:function(a,b){try{var c=J(a);return vc(Ra,c.path,b)}catch(d){if("undefined"==typeof L||"ErrnoError"!==d.name)throw d;return-d.sb}},fa:function(a,b){try{if(0===b)return-28;var c=lb,d=ob(c)+1;if(b<d)return-68;pb(c,v,a,b);return d}catch(e){if("undefined"==typeof L||"ErrnoError"!==e.name)throw e;return-e.sb}},oa:function(a,b,c){wc=c;try{var d=J(a);switch(b){case 21509:return d.tty?
0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Bb.jd){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=xc();y[e>>2]=25856;y[e+4>>2]=5;y[e+8>>2]=191;y[e+12>>2]=35387;for(var f=0;32>f;f++)t[e+f+17>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Bb.kd)for(e=xc(),a=[],f=0;32>f;f++)a.push(t[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=xc();return y[e>>2]=0;case 21520:return d.tty?
-28:-59;case 21531:e=xc();if(!d.rb.hd)throw new E(59);return d.rb.hd(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Bb.ld&&(f=[24,80],e=xc(),ua[e>>1]=f[0],ua[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof L||"ErrnoError"!==h.name)throw h;return-h.sb}},ga:function(a,b){try{return a=a?D(v,a):"",vc(jc,a,b)}catch(c){if("undefined"==typeof L||"ErrnoError"!==c.name)throw c;return-c.sb}},ba:function(a,b,c){try{return b=b?
D(v,b):"",b=uc(a,b),b=fb(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),K(b,c),0}catch(d){if("undefined"==typeof L||"ErrnoError"!==d.name)throw d;return-d.sb}},ha:function(a,b,c,d){try{b=b?D(v,b):"";var e=d&256;b=uc(a,b,d&4096);return vc(e?jc:Ra,b,c)}catch(f){if("undefined"==typeof L||"ErrnoError"!==f.name)throw f;return-f.sb}},I:function(a,b,c,d){wc=d;try{b=b?D(v,b):"";b=uc(a,b);var e=d?xc():0;return Qa(b,c,e).fd}catch(f){if("undefined"==typeof L||"ErrnoError"!==f.name)throw f;return-f.sb}},
aa:function(a,b,c,d){try{b=b?D(v,b):"";b=uc(a,b);if(0>=d)return-28;var e=Sb(b),f=Math.min(d,ob(e)),h=t[c+f];pb(e,v,c,d+1);t[c+f]=h;return f}catch(l){if("undefined"==typeof L||"ErrnoError"!==l.name)throw l;return-l.sb}},_:function(a){try{return a=a?D(v,a):"",hc(a),0}catch(b){if("undefined"==typeof L||"ErrnoError"!==b.name)throw b;return-b.sb}},ia:function(a,b){try{return a=a?D(v,a):"",vc(Ra,a,b)}catch(c){if("undefined"==typeof L||"ErrnoError"!==c.name)throw c;return-c.sb}},$:function(a,b,c){try{return b=
b?D(v,b):"",b=uc(a,b),0===c?ic(b):512===c?hc(b):qa("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof L||"ErrnoError"!==d.name)throw d;return-d.sb}},ka:()=>1,X:()=>{throw Infinity;},Va:function(a,b,c){a=new Date(1E3*Bc(a,b));y[c>>2]=a.getSeconds();y[c+4>>2]=a.getMinutes();y[c+8>>2]=a.getHours();y[c+12>>2]=a.getDate();y[c+16>>2]=a.getMonth();y[c+20>>2]=a.getFullYear()-1900;y[c+24>>2]=a.getDay();y[c+28>>2]=(yc(a.getFullYear())?zc:Ac)[a.getMonth()]+a.getDate()-1|0;y[c+36>>2]=-(60*
a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();y[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Ta:function(a,b,c,d,e,f,h,l){e=Bc(e,f);try{if(isNaN(e))return 61;var n=J(d);if(0!==(b&2)&&0===(c&2)&&2!==(n.flags&2097155))throw new E(2);if(1===(n.flags&2097155))throw new E(2);if(!n.rb.Pb)throw new E(43);var q=n.rb.Pb(n,a,e,b,c);var w=q.tb;y[h>>2]=q.Ac;A[l>>2]=w;return 0}catch(p){if("undefined"==typeof L||
"ErrnoError"!==p.name)throw p;return-p.sb}},Ua:function(a,b,c,d,e,f,h){f=Bc(f,h);try{if(isNaN(f))return 61;var l=J(e);if(c&2){if(32768!==(l.node.mode&61440))throw new E(43);if(!(d&2)){var n=v.slice(a,a+b);l.rb.bc&&l.rb.bc(l,n,f,b,d)}}}catch(q){if("undefined"==typeof L||"ErrnoError"!==q.name)throw q;return-q.sb}},Z:(a,b,c)=>{function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=
h.getTimezoneOffset();A[a>>2]=60*Math.max(e,l);y[b>>2]=Number(e!=l);a=d(f);b=d(h);a=Dc(a);b=Dc(b);l<e?(A[c>>2]=a,A[c+4>>2]=b):(A[c>>2]=b,A[c+4>>2]=a)},p:()=>{qa("")},Na:(a,b,c)=>{Ec.length=0;for(var d;d=v[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Ec.push(112==d?A[c>>2]:105==d?y[c>>2]:wa[c>>3]);c+=e?8:4}return Va[a].apply(null,Ec)},v:()=>{bd();Hc=null},la:()=>Date.now(),x:Lc,ma:(a,b,c)=>v.copyWithin(a,b,b+c),Y:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ra.buffer.byteLength+65535)/65536;try{ra.grow(e);xa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},w:(a,b,c)=>{a=P(a);Yc(a,b,c)},da:(a,b)=>{var c=0;Id().forEach((d,e)=>{var f=b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)t[e++>>0]=d.charCodeAt(f);t[e>>0]=0;c+=d.length+1});return 0},ea:(a,b)=>{var c=Id();A[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);A[b>>2]=d;return 0},o:$c,
z:function(a){try{var b=J(a);Ta(b);return 0}catch(c){if("undefined"==typeof L||"ErrnoError"!==c.name)throw c;return c.sb}},ca:function(a,b){try{var c=J(a);t[b>>0]=c.tty?2:H(c.mode)?3:40960===(c.mode&61440)?7:4;ua[b+2>>1]=0;C=[0,(B=0,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[b+8>>2]=C[0];y[b+12>>2]=C[1];C=[0,(B=0,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[b+16>>2]=C[0];y[b+20>>2]=C[1];
return 0}catch(d){if("undefined"==typeof L||"ErrnoError"!==d.name)throw d;return d.sb}},K:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,h=b=0;h<c;h++){var l=A[a>>2],n=A[a+4>>2];a+=8;var q=Sa(e,t,l,n,f);if(0>q){var w=-1;break a}b+=q;if(q<n)break;"undefined"!==typeof f&&(f+=q)}w=b}A[d>>2]=w;return 0}catch(p){if("undefined"==typeof L||"ErrnoError"!==p.name)throw p;return p.sb}},Wa:function(a,b,c,d,e){b=Bc(b,c);try{if(isNaN(b))return 61;var f=J(a);mc(f,b,d);C=[f.position>>>0,(B=f.position,1<=+Math.abs(B)?
0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];y[e>>2]=C[0];y[e+4>>2]=C[1];f.nc&&0===b&&0===d&&(f.nc=null);return 0}catch(h){if("undefined"==typeof L||"ErrnoError"!==h.name)throw h;return h.sb}},J:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,h=b=0;h<c;h++){var l=A[a>>2],n=A[a+4>>2];a+=8;var q=nc(e,t,l,n,f);if(0>q){var w=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}w=b}A[d>>2]=w;return 0}catch(p){if("undefined"==typeof L||"ErrnoError"!==p.name)throw p;return p.sb}},
S:(a,b)=>{N.attachShader(S[a],T[b])},G:(a,b)=>{34962==a?N.Ub=b:34963==a&&(N.Mb=b);35051==a?N.Ec=b:35052==a&&(N.Fc=b);N.bindBuffer(a,Od[b])},Sa:a=>{N.bindVertexArray(Pd[a]);a=N.getParameter(34965);N.Mb=a?a.name|0:0},Fa:function(a,b){N.blendFunc(a,b)},u:(a,b,c,d)=>{2<=M.version?c&&b?N.bufferData(a,v,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?v.subarray(c,c+b):b,d)},Ka:function(a){N.clear(a)},La:function(a,b,c,d){N.clearColor(a,b,c,d)},xa:a=>{N.compileShader(T[a])},Qa:()=>{var a=Ud(S),b=N.createProgram();
b.name=a;b.$b=b.Yb=b.Zb=0;b.xc=1;S[a]=b;return a},za:a=>{var b=Ud(T);T[b]=N.createShader(a);return b},Ra:(a,b)=>{for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=Od[d];e&&(N.deleteBuffer(e),e.name=0,Od[d]=null,d==N.Ub&&(N.Ub=0),d==N.Mb&&(N.Mb=0),d==N.Ec&&(N.Ec=0),d==N.Fc&&(N.Fc=0))}},va:a=>{if(a){var b=S[a];b?(N.deleteProgram(b),b.name=0,S[a]=null):Sd(1281)}},F:a=>{if(a){var b=T[a];b?(N.deleteShader(b),T[a]=null):Sd(1281)}},H:a=>{if(a){var b=Qd[a];b?(N.deleteSync(b),b.name=0,Qd[a]=null):Sd(1281)}},Ea:function(a){N.depthFunc(a)},
O:(a,b,c,d)=>{if(!N.Mb){var e=1*Rd[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var h=M.Jb[f];h?f=h:(h=N.getParameter(34965),M.Jb[f]=N.createBuffer(),N.bindBuffer(34963,M.Jb[f]),N.bufferData(34963,1<<f,35048),N.bindBuffer(34963,h),f=M.Jb[f]);N.bindBuffer(34963,f);N.bufferSubData(34963,0,v.subarray(d,d+e));d=0}Xd=!1;for(e=0;e<M.Nc;++e)if(f=M.Tb[e],f.fc&&f.enabled){Xd=!0;h=f.vc;h=0<h?b*h:f.size*Rd[f.type-5120]*b;var l=32-Math.clz32(0===h?0:h-1);var n=M.Kb[l],q=M.Cb[l];M.Cb[l]=M.Cb[l]+1&63;var w=n[q];
w?l=w:(w=N.getParameter(34964),n[q]=N.createBuffer(),N.bindBuffer(34962,n[q]),N.bufferData(34962,1<<l,35048),N.bindBuffer(34962,w),l=n[q]);N.bindBuffer(34962,l);N.bufferSubData(34962,0,v.subarray(f.tb,f.tb+h));f.Xc.call(N,e,f.size,f.type,f.Qc,f.vc,0)}N.drawElements(a,b,c,d);Xd&&N.bindBuffer(34962,Od[N.Ub]);N.Mb||N.bindBuffer(34963,null)},E:function(a){N.enable(a)},B:a=>{M.Tb[a].enabled=!0;N.enableVertexAttribArray(a)},T:(a,b)=>{Yd(a,b,"createBuffer",Od)},Ya:function(a,b){Yd(a,b,"createVertexArray",
Pd)},Ma:(a,b,c,d)=>{a=N.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?pb(a,v,d,b):0;c&&(y[c>>2]=b)},R:(a,b,c)=>{if(c)if(a>=Nd)Sd(1281);else if(a=S[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.$b)for(b=0;b<N.getProgramParameter(a,35718);++b)a.$b=Math.max(a.$b,N.getActiveUniform(a,b).name.length+1);y[c>>2]=a.$b}else if(35722==b){if(!a.Yb)for(b=0;b<N.getProgramParameter(a,35721);++b)a.Yb=Math.max(a.Yb,N.getActiveAttrib(a,
b).name.length+1);y[c>>2]=a.Yb}else if(35381==b){if(!a.Zb)for(b=0;b<N.getProgramParameter(a,35382);++b)a.Zb=Math.max(a.Zb,N.getActiveUniformBlockName(a,b).length+1);y[c>>2]=a.Zb}else y[c>>2]=N.getProgramParameter(a,b);else Sd(1281)},wa:(a,b,c,d)=>{a=N.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?pb(a,v,d,b):0;c&&(y[c>>2]=b)},N:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(T[a]),y[c>>2]=a?a.length+
1:0):y[c>>2]=N.getShaderParameter(T[a],b):Sd(1281)},ta:(a,b)=>{b=b?D(v,b):"";if(a=S[a]){var c=a,d=c.Rb,e=c.Wc,f;if(!d)for(c.Rb=d={},c.Vc={},f=0;f<N.getProgramParameter(c,35718);++f){var h=N.getActiveUniform(c,f);var l=h.name;h=h.size;var n=Zd(l);n=0<n?l.slice(0,n):l;var q=c.xc;c.xc+=h;e[n]=[h,q];for(l=0;l<h;++l)d[q]=l,c.Vc[q++]=n}c=a.Rb;d=0;e=b;f=Zd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Wc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else Sd(1281);return-1},
Pa:a=>{a=S[a];N.linkProgram(a);a.Rb=0;a.Wc={}},ya:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var h=(h=A[c+4*f>>2])?D(v,h,d?A[d+4*f>>2]:void 0):"";e+=h}N.shaderSource(T[a],e)},sa:(a,b,c,d)=>{if(2<=M.version)b&&N.uniformMatrix4fv($d(a),!!c,va,d>>2,16*b);else{if(18>=b){var e=ae[16*b-1],f=va;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=
f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=va.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv($d(a),!!c,e)}},ua:a=>{a=S[a];N.useProgram(a);N.dd=a},Oa:a=>{N.validateProgram(S[a])},y:(a,b,c,d,e,f)=>{var h=M.Tb[a];N.Ub?(h.fc=!1,N.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.Qc=d,h.vc=e,h.tb=f,h.fc=!0,h.Xc=function(l,n,q,w,p,u){this.vertexAttribPointer(l,n,q,w,p,u)})},Q:function(a,b,c,d){N.viewport(a,b,c,d)},V:(a,b,c,d)=>{N.waitSync(Qd[a],b,(c>>>0)+4294967296*d)},Ia:(a,b,
c,d)=>{var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?od():Dd(a,b);for(e=0;e<V.length&&null==V[e];e++);a=0<ce[139265];e==V.length&&(a?g.Lb=hd(g.canvas,!0,!0,{antialias:1<ce[135181],depth:0<ce[135173],stencil:0<ce[135174],alpha:0<ce[135172]}):Hb());!g.Lb&&a?f=0:(e=g.canvas,c=new be(f,e.clientWidth,e.clientHeight,e.width,e.height,c),f-1==V.length?V.push(c):V[f-1]=c,U=c,Ke(),f=c.id)}return f},Ba:(a,
b,c)=>{var d=0,e=0;if(a=0>=a||!V?null:V[a-1])d=a.width,e=a.height;b&&(y[b>>2]=d);c&&(y[c>>2]=e)},Ja:()=>{if(V)return 1;Lc();ce=Object.assign({},ge);V=[];U=null;de=Je();window.addEventListener("gamepadconnected",me,!0);window.addEventListener("gamepaddisconnected",ne,!0);window.addEventListener("keydown",oe,!0);window.addEventListener("keypress",je,!0);window.addEventListener("keyup",pe,!0);window.addEventListener("blur",qe,!0);ee=window.matchMedia("(resolution: "+Je()+"dppx)");ee.addEventListener("change",
Le);g.canvas.addEventListener("touchmove",re,!0);g.canvas.addEventListener("touchstart",we,!0);g.canvas.addEventListener("touchcancel",xe,!0);g.canvas.addEventListener("touchend",xe,!0);g.canvas.addEventListener("mousemove",re,!0);g.canvas.addEventListener("mousedown",we,!0);g.canvas.addEventListener("mouseup",xe,!0);g.canvas.addEventListener("wheel",ye,!0);g.canvas.addEventListener("mousewheel",ye,!0);g.canvas.addEventListener("mouseenter",se,!0);g.canvas.addEventListener("mouseleave",ue,!0);g.canvas.addEventListener("drop",
Ee,!0);g.canvas.addEventListener("dragover",Fe,!0);od=Ge;yd=Ie;rd=He;Bd.push((a,b)=>{if(U&&0<U.attributes[139276]){var c=g.canvas;ze(c.clientWidth,c.clientHeight,a,b)}else ze(a,b,a,b)});return 1},Ha:()=>{},Aa:()=>{},Ga:(a,b)=>{a=0>=a||!V?null:V[a-1];if(!a)return null;var c=a.Wb;a.Wb=b;return c},Ca:()=>{},P:(a,b)=>{ce[a]=b},Da:a=>(a=0>=a||!V?null:V[a-1])?a.qd:0,e:Ue,M:Ve,f:We,c:Xe,n:Ye,t:Ze,pa:$e,qa:af,C:bf,U:cf,l:df,h:ef,g:ff,i:gf,j:hf,D:jf,k:kf,Xa:lf,r:a=>a,W:(a,b,c,d)=>Oe(a,b,c,d)},X=function(){function a(c){X=
c.exports;ra=X.Za;xa();Fd=X.ab;Aa.unshift(X._a);Ia("wasm-instantiate");return X}var b={a:mf};Ha("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return m(`Module.instantiateWasm callback failed with error: ${c}`),!1}Pa(b,function(c){a(c.instance)});return{}}(),nf=g._main=(a,b)=>(nf=g._main=X.$a)(a,b),Cc=a=>(Cc=X.bb)(a),De=a=>(De=X.cb)(a),bb=a=>(bb=X.db)(a),xb=(a,b)=>(xb=X.eb)(a,b),W=(a,b)=>(W=X.fb)(a,b),Y=()=>(Y=X.gb)(),Z=a=>(Z=X.hb)(a),of=a=>(of=X.ib)(a),Te=a=>
(Te=X.jb)(a),Re=a=>(Re=X.kb)(a),cb=(a,b,c)=>(cb=X.lb)(a,b,c),Se=a=>(Se=X.mb)(a),pf=g.dynCall_iij=(a,b,c,d)=>(pf=g.dynCall_iij=X.nb)(a,b,c,d),qf=g.dynCall_vij=(a,b,c,d)=>(qf=g.dynCall_vij=X.ob)(a,b,c,d);function gf(a,b,c,d){var e=Y();try{P(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function We(a,b,c){var d=Y();try{return P(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Xe(a,b,c,d){var e=Y();try{return P(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function Ue(a,b){var c=Y();try{return P(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function ff(a,b,c){var d=Y();try{P(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function ef(a,b){var c=Y();try{P(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function jf(a,b,c,d,e,f){var h=Y();try{P(a)(b,c,d,e,f)}catch(l){Z(h);if(l!==l+0)throw l;W(1,0)}}function Ze(a,b,c,d,e,f){var h=Y();try{return P(a)(b,c,d,e,f)}catch(l){Z(h);if(l!==l+0)throw l;W(1,0)}}
function kf(a,b,c,d,e,f,h){var l=Y();try{P(a)(b,c,d,e,f,h)}catch(n){Z(l);if(n!==n+0)throw n;W(1,0)}}function hf(a,b,c,d,e){var f=Y();try{P(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}function Ye(a,b,c,d,e){var f=Y();try{return P(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}function bf(a,b,c,d,e,f,h,l,n,q){var w=Y();try{return P(a)(b,c,d,e,f,h,l,n,q)}catch(p){Z(w);if(p!==p+0)throw p;W(1,0)}}function df(a){var b=Y();try{P(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}
function Ve(a,b,c){var d=Y();try{return P(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function af(a,b,c,d,e,f,h,l,n){var q=Y();try{return P(a)(b,c,d,e,f,h,l,n)}catch(w){Z(q);if(w!==w+0)throw w;W(1,0)}}function $e(a,b,c,d,e,f,h){var l=Y();try{return P(a)(b,c,d,e,f,h)}catch(n){Z(l);if(n!==n+0)throw n;W(1,0)}}function cf(a,b,c,d){var e=Y();try{return pf(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function lf(a,b,c,d){var e=Y();try{qf(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
g.addRunDependency=Ha;g.removeRunDependency=Ia;g.FS_createPath=pc;g.FS_createLazyFile=tc;g.FS_createDevice=rc;g.FS_createPreloadedFile=Kb;g.FS_createDataFile=Jb;g.FS_unlink=ic;var rf;Ga=function sf(){rf||tf();rf||(Ga=sf)};function uf(a=[]){var b=nf;a.unshift(ca);var c=a.length,d=of(4*(c+1)),e=d;a.forEach(h=>{var l=A,n=e>>2,q=ob(h)+1,w=of(q);pb(h,v,w,q);l[n]=w;e+=4});A[e>>2]=0;try{var f=b(c,d);$c(f,!0)}catch(h){Xc(h)}}
function tf(){var a=ba;function b(){if(!rf&&(rf=!0,g.calledRun=!0,!sa)){g.noFSInit||oc||(oc=!0,g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?rc("/dev","stdin",g.stdin):gc("/dev/tty","/dev/stdin"),g.stdout?rc("/dev","stdout",null,g.stdout):gc("/dev/tty","/dev/stdout"),g.stderr?rc("/dev","stderr",null,g.stderr):gc("/dev/tty1","/dev/stderr"),Qa("/dev/stdin",0),Qa("/dev/stdout",1),Qa("/dev/stderr",1));Rb=!1;Wa(Aa);Wa(Ba);if(g.onRuntimeInitialized)g.onRuntimeInitialized();vf&&uf(a);if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ca.unshift(c)}Wa(Ca)}}if(!(0<Ea)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Da();Wa(ya);0<Ea||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var vf=!0;g.noInitialRun&&(vf=!1);tf();
