var g;g||=typeof Module !== 'undefined' ? Module : {};g.Ac||(g.Ac=0);g.Ac++;
g.ENVIRONMENT_IS_PTHREAD||g.$ww||function(a){function b(m,q,w,r){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(m,function(k,x){k?r(k):w(x.buffer)});else{var u=new XMLHttpRequest;u.open("GET",m,!0);u.responseType="arraybuffer";u.onprogress=function(k){var x=q;k.total&&(x=k.total);if(k.loaded){u.Hb?g.Sb[m].loaded=k.loaded:(u.Hb=!0,g.Sb||(g.Sb={}),g.Sb[m]={loaded:k.loaded,total:x});var z=x=k=0,F;for(F in g.Sb){var S=g.Sb[F];
k+=S.total;x+=S.loaded;z++}k=Math.ceil(k*g.Ac/z);g.setStatus&&g.setStatus(`Downloading data... (${x}/${k})`)}else!g.Sb&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+m);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)w(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}}function c(m){console.error("package error:",m)}function d(){function m(u,k,x){this.start=u;this.end=
k;this.audio=x}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);m.prototype.nd=u;u=a.files;for(var k=0;k<u.length;++k)m.prototype.Hb[u[k].filename].onload();g.removeRunDependency("datafile_Test/Test.data")}g.FS_createPath("/","assets",!0,!0);m.prototype={Hb:{},open:function(u,k){this.name=k;this.Hb[k]=this;g.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.vc(this.nd.subarray(this.start,
this.end))},vc:function(u){g.FS_createDataFile(this.name,null,u,!0,!0,!0);g.removeRunDependency(`fp ${this.name}`);this.Hb[this.name]=null}};for(var w=a.files,r=0;r<w.length;++r)(new m(w[r].start,w[r].end,w[r].audio||0)).open("GET",w[r].filename);g.addRunDependency("datafile_Test/Test.data");g.cd||(g.cd={});g.cd["Test/Test.data"]={Ud:!1};l?(q(l),l=null):h=q}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,n("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("Test.data",""):"Test.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?
g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/assets/Roboto.ttf",start:0,end:168260},{filename:"/assets/RobotoMono.ttf",start:168260,end:255496},{filename:"/assets/cube.obj",start:255496,end:256759},{filename:"/assets/teapot.obj",start:256759,end:797339},{filename:"/assets/text.txt",start:797339,end:797350}],remote_package_size:797350});
var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ia="",ja,ka,la;
if(ha){var fs=require("fs"),ma=require("path");ia=fa?ma.dirname(ia)+"/":__dirname+"/";ja=(a,b)=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a};ka=(a,b,c,d=!0)=>{a=na(a)?new URL(a):ma.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!g.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);
process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||fa)fa?ia=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ia=document.currentScript.src),ia=ia.startsWith("blob:")?"":ia.substr(0,ia.replace(/[?#].*/,"").lastIndexOf("/")+1),ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=g.print||console.log.bind(console),n=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var qa;g.wasmBinary&&(qa=g.wasmBinary);
"object"!=typeof WebAssembly&&ra("no native wasm support detected");var sa,ta=!1,ua,p,t,va,wa,v,y,xa,ya;function za(){var a=sa.buffer;g.HEAP8=p=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAPU8=t=new Uint8Array(a);g.HEAPU16=wa=new Uint16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU32=y=new Uint32Array(a);g.HEAPF32=xa=new Float32Array(a);g.HEAPF64=ya=new Float64Array(a)}var Aa=[],Ca=[],Da=[],Ea=[];function Fa(){var a=g.preRun.shift();Aa.unshift(a)}var Ga=0,Ha=null,Ia=null;
function Ja(){Ga++;g.monitorRunDependencies?.(Ga)}function Ka(){Ga--;g.monitorRunDependencies?.(Ga);if(0==Ga&&(null!==Ha&&(clearInterval(Ha),Ha=null),Ia)){var a=Ia;Ia=null;a()}}function ra(a){g.onAbort?.(a);a="Aborted("+a+")";n(a);ta=!0;ua=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var La=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ma;Ma="Test.wasm";if(!La(Ma)){var Na=Ma;Ma=g.locateFile?g.locateFile(Na,ia):ia+Na}
function Oa(a){if(a==Ma&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function Pa(a){if(!qa&&(ea||fa)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Oa(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Oa(a))}
function Qa(a,b,c){return Pa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);ra(d)})}function Ra(a,b){var c=Ma;qa||"function"!=typeof WebAssembly.instantiateStreaming||La(c)||na(c)||ha||"function"!=typeof fetch?Qa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Qa(c,a,b)}))}
var A,B,Xa={1030564:()=>{var a=a||"binary";if("utf8"!==a&&"binary"!==a)throw Error(`Invalid encoding type "${a}"`);var b;var c=Sa("FontAtlasGeneration.png",c||0);var d=Ta("FontAtlasGeneration.png").size,e=new Uint8Array(d);Va(c,e,0,d,0);"utf8"===a?b=C(e,0):"binary"===a&&(b=e);Wa(c);a=new Blob([b],{type:"application/octet-stream"});b=document.createElement("a");document.body.appendChild(b);b.href=URL.createObjectURL(a);b.download="FontAtlasGeneration.png";b.click();document.body.removeChild(b);URL.revokeObjectURL(b.href)}};
function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ya=a=>{for(;0<a.length;)a.shift()(g)},Za=g.noExitRuntime||!0,$a=[],ab=0,bb=0;class cb{constructor(a){this.$b=a;this.Fb=a-24}}
var fb=a=>{var b=bb;if(!b)return db(0),0;var c=new cb(b);y[c.Fb+16>>2]=b;var d=y[c.Fb+4>>2];if(!d)return db(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(eb(f,d,c.Fb+16))return db(f),b}db(d);return b},gb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},hb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&
c&&(a+="/");return(b?"/":"")+a},ib=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},jb=a=>{if("/"===a)return"/";a=hb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},kb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ha)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);
var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}ra("initRandomDevice")},lb=a=>(lb=kb())(a);function mb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:nb;if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var ob="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ob)return ob.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
pb=[],qb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},rb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&
63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function sb(a,b){var c=Array(qb(a)+1);a=rb(a,c,0,c.length);b&&(c.length=a);return c}var tb=[];function ub(a,b){tb[a]={input:[],output:[],Nb:b};vb(a,wb)}
var wb={open(a){var b=tb[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.Nb.fsync(a.tty)},fsync(a){a.tty.Nb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Nb.Wc)throw new D(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Nb.Wc(a.tty)}catch(l){throw new D(29);}if(void 0===h&&0===e)throw new D(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Nb.Gc)throw new D(60);try{for(var e=0;e<d;e++)a.tty.Nb.Gc(a.tty,b[c+
e])}catch(f){throw new D(29);}d&&(a.node.timestamp=Date.now());return e}},xb={Wc(){a:{if(!pb.length){var a=null;if(ha){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}pb=sb(a,!0)}a=
pb.shift()}return a},Gc(a,b){null===b||10===b?(pa(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(C(a.output,0)),a.output=[])},wd(){return{Od:25856,Qd:5,Nd:191,Pd:35387,Md:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},xd(){return 0},yd(){return[24,80]}},yb={Gc(a,b){null===b||10===b?(n(C(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(n(C(a.output,0)),a.output=[])}},Ab=a=>{a=65536*
Math.ceil(a/65536);var b=zb(65536,a);b?(t.fill(0,b,b+a),a=b):a=0;return a};function Bb(a,b){var c=a.Cb?a.Cb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Cb,a.Cb=new Uint8Array(b),0<a.Gb&&a.Cb.set(c.subarray(0,a.Gb),0))}
var E={Kb:null,Mb(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);E.Kb||(E.Kb={dir:{node:{Jb:E.Bb.Jb,Ib:E.Bb.Ib,lookup:E.Bb.lookup,pc:E.Bb.pc,rename:E.Bb.rename,unlink:E.Bb.unlink,rmdir:E.Bb.rmdir,readdir:E.Bb.readdir,symlink:E.Bb.symlink},stream:{Pb:E.Db.Pb}},file:{node:{Jb:E.Bb.Jb,Ib:E.Bb.Ib},stream:{Pb:E.Db.Pb,read:E.Db.read,write:E.Db.write,Oc:E.Db.Oc,bc:E.Db.bc,rc:E.Db.rc}},link:{node:{Jb:E.Bb.Jb,Ib:E.Bb.Ib,readlink:E.Bb.readlink},
stream:{}},Sc:{node:{Jb:E.Bb.Jb,Ib:E.Bb.Ib},stream:Cb}});c=Db(a,b,c,d);G(c.mode)?(c.Bb=E.Kb.dir.node,c.Db=E.Kb.dir.stream,c.Cb={}):32768===(c.mode&61440)?(c.Bb=E.Kb.file.node,c.Db=E.Kb.file.stream,c.Gb=0,c.Cb=null):40960===(c.mode&61440)?(c.Bb=E.Kb.link.node,c.Db=E.Kb.link.stream):8192===(c.mode&61440)&&(c.Bb=E.Kb.Sc.node,c.Db=E.Kb.Sc.stream);c.timestamp=Date.now();a&&(a.Cb[b]=c,a.timestamp=c.timestamp);return c},Wd(a){return a.Cb?a.Cb.subarray?a.Cb.subarray(0,a.Gb):new Uint8Array(a.Cb):new Uint8Array(0)},
Bb:{Jb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;G(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Gb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.qd=4096;b.blocks=Math.ceil(b.size/b.qd);return b},Ib(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Gb!=b))if(0==
b)a.Cb=null,a.Gb=0;else{var c=a.Cb;a.Cb=new Uint8Array(b);c&&a.Cb.set(c.subarray(0,Math.min(b,a.Gb)));a.Gb=b}},lookup(){throw Eb[44];},pc(a,b,c,d){return E.createNode(a,b,c,d)},rename(a,b,c){if(G(a.mode)){try{var d=Fb(b,c)}catch(f){}if(d)for(var e in d.Cb)throw new D(55);}delete a.parent.Cb[a.name];a.parent.timestamp=Date.now();a.name=c;b.Cb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.Cb[b];a.timestamp=Date.now()},rmdir(a,b){var c=Fb(a,b),d;for(d in c.Cb)throw new D(55);delete a.Cb[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.Cb))b.push(c);return b},symlink(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},Db:{read(a,b,c,d,e){var f=a.node.Cb;if(e>=a.node.Gb)return 0;a=Math.min(a.node.Gb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();
if(b.subarray&&(!a.Cb||a.Cb.subarray)){if(f)return a.Cb=b.subarray(c,c+d),a.Gb=d;if(0===a.Gb&&0===e)return a.Cb=b.slice(c,c+d),a.Gb=d;if(e+d<=a.Gb)return a.Cb.set(b.subarray(c,c+d),e),d}Bb(a,e+d);if(a.Cb.subarray&&b.subarray)a.Cb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Cb[e+f]=b[c+f];a.Gb=Math.max(a.Gb,e+d);return d},Pb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Gb);if(0>b)throw new D(28);return b},Oc(a,b,c){Bb(a.node,b+c);a.node.Gb=Math.max(a.node.Gb,b+c)},
bc(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.Cb;if(e&2||a.buffer!==p.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=Ab(b);if(!b)throw new D(48);p.set(a,b)}else c=!1,b=a.byteOffset;return{Fb:b,Pc:c}},rc(a,b,c,d){E.Db.write(a,b,0,d,c,!1);return 0}}},Gb=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{b(new Uint8Array(e));d&&Ka(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ja(d)},Hb=g.preloadPlugins||[],Kb=(a,
b,c,d)=>{"undefined"!=typeof Ib&&Jb();var e=!1;Hb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Mb=(a,b,c,d,e,f,h,l,m,q)=>{function w(k){function x(z){q?.();l||Lb(a,b,z,d,e,m);f?.();Ka(u)}Kb(k,r,x,()=>{h?.();Ka(u)})||x(k)}var r=b?mb(hb(a+"/"+b)):a,u=`cp ${r}`;Ja(u);"string"==typeof c?Gb(c,w,h):w(c)},Nb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Ob=null,Pb={},Qb=[],Rb=1,Sb=null,nb="/",Tb=!0,D=class{constructor(a){this.name="ErrnoError";this.Eb=a}},Eb={};
function H(a,b={}){a=mb(a);if(!a)return{path:"",node:null};b=Object.assign({Vc:!0,Hc:0},b);if(8<b.Hc)throw new D(32);a=a.split("/").filter(h=>!!h);for(var c=Ob,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Fb(c,a[e]);d=hb(d+"/"+a[e]);c.Tb&&(!f||f&&b.Vc)&&(c=c.Tb.root);if(!f||b.ac)for(f=0;40960===(c.mode&61440);)if(c=Ub(d),d=mb(ib(d),c),c=H(d,{Hc:b.Hc+1}).node,40<f++)throw new D(32);}return{path:d,node:c}}
function Vb(a){for(var b;;){if(a===a.parent)return a=a.Mb.ad,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Wb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Sb.length}function Xb(a){var b=Wb(a.parent.id,a.name);if(Sb[b]===a)Sb[b]=a.Ub;else for(b=Sb[b];b;){if(b.Ub===a){b.Ub=a.Ub;break}b=b.Ub}}
function Fb(a,b){var c=G(a.mode)?(c=Yb(a,"x"))?c:a.Bb.lookup?0:2:54;if(c)throw new D(c);for(c=Sb[Wb(a.id,b)];c;c=c.Ub){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Bb.lookup(a,b)}function Db(a,b,c,d){a=new Zb(a,b,c,d);b=Wb(a.parent.id,a.name);a.Ub=Sb[b];return Sb[b]=a}function G(a){return 16384===(a&61440)}function $b(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Yb(a,b){if(Tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ac(a,b){try{return Fb(a,b),20}catch(c){}return Yb(a,"wx")}function bc(a,b,c){try{var d=Fb(a,b)}catch(e){return e.Eb}if(a=Yb(a,"wx"))return a;if(c){if(!G(d.mode))return 54;if(d===d.parent||Vb(d)===nb)return 10}else if(G(d.mode))return 31;return 0}function cc(){for(var a=0;4096>=a;a++)if(!Qb[a])return a;throw new D(33);}
function I(a){a=Qb[a];if(!a)throw new D(8);return a}function dc(a,b=-1){ec||(ec=function(){this.Hb={}},ec.prototype={},Object.defineProperties(ec.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.Hb.flags},set(c){this.Hb.flags=c}},position:{get(){return this.Hb.position},set(c){this.Hb.position=c}}}));a=Object.assign(new ec,a);-1==b&&(b=cc());a.fd=b;return Qb[b]=a}var Cb={open(a){a.Db=Pb[a.node.rdev].Db;a.Db.open?.(a)},Pb(){throw new D(70);}};
function vb(a,b){Pb[a]={Db:b}}function fc(a,b){var c="/"===b;if(c&&Ob)throw new D(10);if(!c&&b){var d=H(b,{Vc:!1});b=d.path;d=d.node;if(d.Tb)throw new D(10);if(!G(d.mode))throw new D(54);}b={type:a,ce:{},ad:b,Bd:[]};a=a.Mb(b);a.Mb=b;b.root=a;c?Ob=a:d&&(d.Tb=b,d.Mb&&d.Mb.Bd.push(b))}function gc(a,b,c){var d=H(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new D(28);var e=ac(d,a);if(e)throw new D(e);if(!d.Bb.pc)throw new D(63);return d.Bb.pc(d,a,b,c)}
function J(a,b){return gc(a,(void 0!==b?b:511)&1023|16384,0)}function hc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return gc(a,b|8192,c)}function ic(a,b){if(!mb(a))throw new D(44);var c=H(b,{parent:!0}).node;if(!c)throw new D(44);b=jb(b);var d=ac(c,b);if(d)throw new D(d);if(!c.Bb.symlink)throw new D(63);c.Bb.symlink(c,b,a)}function jc(a){var b=H(a,{parent:!0}).node;a=jb(a);var c=Fb(b,a),d=bc(b,a,!0);if(d)throw new D(d);if(!b.Bb.rmdir)throw new D(63);if(c.Tb)throw new D(10);b.Bb.rmdir(b,a);Xb(c)}
function kc(a){var b=H(a,{parent:!0}).node;if(!b)throw new D(44);a=jb(a);var c=Fb(b,a),d=bc(b,a,!1);if(d)throw new D(d);if(!b.Bb.unlink)throw new D(63);if(c.Tb)throw new D(10);b.Bb.unlink(b,a);Xb(c)}function Ub(a){a=H(a).node;if(!a)throw new D(44);if(!a.Bb.readlink)throw new D(28);return mb(Vb(a.parent),a.Bb.readlink(a))}function Ta(a,b){a=H(a,{ac:!b}).node;if(!a)throw new D(44);if(!a.Bb.Jb)throw new D(63);return a.Bb.Jb(a)}function lc(a){return Ta(a,!0)}
function mc(a,b){a="string"==typeof a?H(a,{ac:!0}).node:a;if(!a.Bb.Ib)throw new D(63);a.Bb.Ib(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Sa(a,b,c){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=hb(a);try{e=H(a,{ac:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new D(20);}else e=gc(a,c,0),d=!0;if(!e)throw new D(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!G(e.mode))throw new D(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:G(e.mode)&&("r"!==$b(b)||b&512)?31:Yb(e,$b(b)):44))throw new D(c);if(b&512&&!d){c=e;c="string"==typeof c?H(c,{ac:!0}).node:c;if(!c.Bb.Ib)throw new D(63);if(G(c.mode))throw new D(31);if(32768!==(c.mode&61440))throw new D(28);if(d=Yb(c,"w"))throw new D(d);c.Bb.Ib(c,{size:0,timestamp:Date.now()})}b&=-131713;e=dc({node:e,path:Vb(e),flags:b,seekable:!0,position:0,Db:e.Db,Hd:[],error:!1});e.Db.open&&e.Db.open(e);!g.logReadFiles||b&1||(nc||={},a in nc||(nc[a]=1));return e}
function Wa(a){if(null===a.fd)throw new D(8);a.Dc&&(a.Dc=null);try{a.Db.close&&a.Db.close(a)}catch(b){throw b;}finally{Qb[a.fd]=null}a.fd=null}function oc(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.Db.Pb)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.Db.Pb(a,b,c);a.Hd=[]}
function Va(a,b,c,d,e){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(1===(a.flags&2097155))throw new D(8);if(G(a.node.mode))throw new D(31);if(!a.Db.read)throw new D(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new D(70);b=a.Db.read(a,b,c,d,e);f||(a.position+=b);return b}
function pc(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(G(a.node.mode))throw new D(31);if(!a.Db.write)throw new D(28);a.seekable&&a.flags&1024&&oc(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new D(70);b=a.Db.write(a,b,c,d,e,f);h||(a.position+=b);return b}var qc;
function rc(a,b){a="string"==typeof a?a:Vb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=hb(a+"/"+c);try{J(d)}catch(e){}a=d}}return d}function sc(a,b,c,d){a=hb(("string"==typeof a?a:Vb(a))+"/"+b);c=Nb(c,d);return gc(a,(void 0!==c?c:438)&4095|32768,0)}
function Lb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Vb(a),h=b?hb(a+"/"+b):a);a=Nb(d,e);h=gc(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}mc(h,a|146);b=Sa(h,577);pc(b,c,0,c.length,0,f);Wa(b);mc(h,a)}}
function tc(a,b,c,d){a=hb(("string"==typeof a?a:Vb(a))+"/"+b);b=Nb(!!c,!!d);tc.Yc||(tc.Yc=64);var e=tc.Yc++<<8|0;vb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,l,m){for(var q=0,w=0;w<m;w++){try{var r=c()}catch(u){throw new D(29);}if(void 0===r&&0===q)throw new D(6);if(null===r||void 0===r)break;q++;h[l+w]=r}q&&(f.node.timestamp=Date.now());return q},write(f,h,l,m){for(var q=0;q<m;q++)try{d(h[l+q])}catch(w){throw new D(29);}m&&(f.node.timestamp=Date.now());return q}});return hc(a,
b,e)}function uc(a){if(!(a.zd||a.Ad||a.link||a.Cb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.Cb=sb(ja(a.url),!0),a.Gb=a.Cb.length}catch(b){throw new D(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function vc(a,b,c,d,e){function f(){this.Fc=!1;this.Hb=[]}function h(r,u,k,x,z){r=r.node.Cb;if(z>=r.length)return 0;x=Math.min(r.length-z,x);if(r.slice)for(var F=0;F<x;F++)u[k+F]=r[z+F];else for(F=0;F<x;F++)u[k+F]=r.get(z+F);return x}f.prototype.get=function(r){if(!(r>this.length-1||0>r)){var u=r%this.chunkSize;return this.Xc(r/this.chunkSize|0)[u]}};f.prototype.vc=function(r){this.Xc=r};f.prototype.Qc=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||
304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var u=Number(r.getResponseHeader("Content-length")),k,x=(k=r.getResponseHeader("Accept-Ranges"))&&"bytes"===k;r=(k=r.getResponseHeader("Content-Encoding"))&&"gzip"===k;var z=1048576;x||(z=u);var F=this;F.vc(S=>{var Ua=S*z,Ba=(S+1)*z-1;Ba=Math.min(Ba,u-1);if("undefined"==typeof F.Hb[S]){var we=F.Hb;if(Ua>Ba)throw Error("invalid range ("+Ua+", "+Ba+") or no bytes requested!");if(Ba>u-1)throw Error("only "+u+" bytes available! programmer error!");
var R=new XMLHttpRequest;R.open("GET",c,!1);u!==z&&R.setRequestHeader("Range","bytes="+Ua+"-"+Ba);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);Ua=void 0!==R.response?new Uint8Array(R.response||[]):sb(R.responseText||"",!0);we[S]=Ua}if("undefined"==typeof F.Hb[S])throw Error("doXHR failed!");return F.Hb[S]});if(r||!u)z=u=1,
z=u=this.Xc(0).length,pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.pd=u;this.od=z;this.Fc=!0};if("undefined"!=typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new f;Object.defineProperties(l,{length:{get:function(){this.Fc||this.Qc();return this.pd}},chunkSize:{get:function(){this.Fc||this.Qc();return this.od}}});var m=void 0}else m=c,l=void 0;var q=
sc(a,b,d,e);l?q.Cb=l:m&&(q.Cb=null,q.url=m);Object.defineProperties(q,{Gb:{get:function(){return this.Cb.length}}});var w={};Object.keys(q.Db).forEach(r=>{var u=q.Db[r];w[r]=function(){uc(q);return u.apply(null,arguments)}});w.read=(r,u,k,x,z)=>{uc(q);return h(r,u,k,x,z)};w.bc=(r,u,k)=>{uc(q);var x=Ab(u);if(!x)throw new D(48);h(r,p,x,u,k);return{Fb:x,Pc:!0}};q.Db=w;return q}var K={},ec,nc;
function wc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?nb:I(a).path;if(0==b.length){if(!c)throw new D(44);return a}return hb(a+"/"+b)}
function xc(a,b,c){a=a(b);v[c>>2]=a.dev;v[c+4>>2]=a.mode;y[c+8>>2]=a.nlink;v[c+12>>2]=a.uid;v[c+16>>2]=a.gid;v[c+20>>2]=a.rdev;B=[a.size>>>0,(A=a.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+24>>2]=B[0];v[c+28>>2]=B[1];v[c+32>>2]=4096;v[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();B=[Math.floor(b/1E3)>>>0,(A=Math.floor(b/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>
0))/4294967296)>>>0:0)];v[c+40>>2]=B[0];v[c+44>>2]=B[1];y[c+48>>2]=b%1E3*1E3;B=[Math.floor(d/1E3)>>>0,(A=Math.floor(d/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+56>>2]=B[0];v[c+60>>2]=B[1];y[c+64>>2]=d%1E3*1E3;B=[Math.floor(e/1E3)>>>0,(A=Math.floor(e/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+72>>2]=B[0];v[c+76>>2]=B[1];y[c+80>>2]=e%1E3*1E3;B=[a.ino>>>0,(A=a.ino,1<=+Math.abs(A)?
0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+88>>2]=B[0];v[c+92>>2]=B[1];return 0}var yc=void 0;function zc(){var a=v[+yc>>2];yc+=4;return a}
var Ac=a=>0===a%4&&(0!==a%100||0===a%400),Bc=[0,31,60,91,121,152,182,213,244,274,305,335],Cc=[0,31,59,90,120,151,181,212,243,273,304,334],Dc=(a,b)=>b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN,Fc=a=>{var b=qb(a)+1,c=Ec(b);c&&rb(a,t,c,b);return c},Gc=[],Rc=(a,b)=>{Hc=a;Ic=b;if(Jc)if(Kc||=!0,0==a)Lc=function(){var d=Math.max(0,Mc+b-Nc())|0;setTimeout(Oc,d)};else if(1==a)Lc=function(){Pc(Oc)};else if(2==a){if("undefined"==typeof Qc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",
d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qc=function(d){c.push(d);fa?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Qc=setImmediate;Lc=function(){Qc(Oc)}}},Nc;Nc=()=>performance.now();
var $c=(a,b,c,d,e)=>{!Jc||ra("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Jc=a;Sc=d;var f=Tc;Kc=!1;Oc=function(){if(!ta)if(0<Uc.length){var h=Uc.shift();h.Vd(h.Jd);if(Vc){var l=Vc,m=0==l%1?l-1:Math.floor(l);Vc=h.Rd?m:(8*l+(m+.5))/9}g.setStatus&&(h=g.statusMessage||"Please wait...",l=Vc,m=Wc.Td,l?l<m?g.setStatus(h+" ("+(m-l)+"/"+m+")"):g.setStatus(h):g.setStatus(""));
f<Tc||setTimeout(Oc,0)}else if(!(f<Tc))if(Xc=Xc+1|0,1==Hc&&1<Ic&&0!=Xc%Ic)Lc();else{0==Hc&&(Mc=Nc());if(L)for(h=L.Wb,L.Wb=L.cc,L.cc=h,h=L.Ob,L.Ob=L.sc,L.sc=h,h=0;21>=h;++h)L.Ob[h]=0;if(!(ta||g.preMainLoop&&!1===g.preMainLoop())){if(!ta)try{a(),Yc()}catch(q){Zc(q)}g.postMainLoop?.()}f<Tc||("object"==typeof SDL&&SDL.audio?.de?.(),Lc())}};e||(b&&0<b?Rc(0,1E3/b):Rc(1,1),Lc());if(c)throw"unwind";},Zc=a=>{a instanceof oa||"unwind"==a||da(1,a)},ad=a=>{ua=a;Za||(g.onExit?.(a),ta=!0);da(a,new oa(a))},bd=a=>
{ua=a;ad(a)},Yc=()=>{if(!Za)try{var a=ua;ua=a;ad(a)}catch(b){Zc(b)}},cd=a=>{setTimeout(()=>{if(!ta)try{a(),Yc()}catch(b){Zc(b)}},1E4)},Kc=!1,Lc=null,Tc=0,Jc=null,Sc=0,Hc=0,Ic=0,Xc=0,Uc=[];function dd(){Lc=null;Tc++}var Wc={},Mc,Oc,Vc,ed=!1,fd=!1,gd=[];
function Jb(){function a(){fd=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!hd){hd=!0;Hb.push({canHandle:function(c){return!g.be&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=new Blob([c],{type:jd(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:jd(d)}));var l=URL.createObjectURL(h),m=new Image;m.onload=()=>{m.complete||ra(`Image ${d} could not be decoded`);
var q=document.createElement("canvas");q.width=m.width;q.height=m.height;q.getContext("2d").drawImage(m,0,0);URL.revokeObjectURL(l);e?.(c)};m.onerror=()=>{n(`Image ${l} could not be decoded`);f?.()};m.src=l}});Hb.push({canHandle:function(c){return!g.ae&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){h||(h=!0,e?.(c))}var h=!1,l=URL.createObjectURL(new Blob([c],{type:jd(d)})),m=new Audio;m.addEventListener("canplaythrough",()=>f(m),!1);m.onerror=function(){if(!h){n(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var q="",w=0,r=0,u=0;u<c.length;u++)for(w=w<<8|c[u],r+=8;6<=r;){var k=w>>r-6&63;r-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[k]}2==r?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],q+="=="):4==r&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],q+="=");m.src="data:audio/x-"+d.substr(-3)+";base64,"+q;f(m)}};m.src=l;cd(()=>{f(m)})}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",
c=>{!fd&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function kd(a,b,c,d){if(b&&g.Xb&&a==g.canvas)return g.Xb;var e;if(b){var f={antialias:!1,alpha:!1,Zc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof ld&&(e=md(a,f)))var l=nd[e].ec}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof M||ra("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Xb=l,b&&(L=nd[e],g.Xb=M=L?.ec),g.ge=b,gd.forEach(m=>m()),Jb());return l}var od=!1,pd=void 0,N=void 0;
function qd(a,b){function c(){ed=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=rd,pd&&d.requestPointerLock(),ed=!0,N?sd():td(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),N?ud():td(d));g.onFullScreen?.(ed);g.onFullscreen?.(ed)}pd=a;N=b;"undefined"==typeof pd&&(pd=!0);"undefined"==typeof N&&(N=!1);var d=g.canvas;od||(od=
!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?
()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function rd(){if(!ed)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var vd=0;function Pc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===vd)vd=b+1E3/60;else for(;b+2>=vd;)vd+=1E3/60;setTimeout(a,Math.max(vd-b,0))}}
function jd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var wd=0,xd=0,yd=0,zd=0;function Ad(a,b){var c=g.canvas.getBoundingClientRect(),d=g.canvas.height;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=g.canvas.width/c.width;b*=d/c.height;return{x:a,y:b}}
function Bd(a,b){const {x:c,y:d}=Ad(a,b);yd=c-wd;zd=d-xd;wd=c;xd=d}function Cd(a){fd?("mousemove"!=a.type&&"mozMovementX"in a?yd=zd=0:(yd=a.movementX||a.mozMovementX||a.webkitMovementX||0,zd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(wd=SDL.Yd+yd,xd=SDL.Zd+zd):(wd+=yd,xd+=zd)):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.fe,void 0!==a&&Ad(a.pageX,a.pageY)):Bd(a.pageX,a.pageY)}var Dd=[];
function Ed(){var a=g.canvas;Dd.forEach(b=>b(a.width,a.height))}function Fd(a,b,c){td(g.canvas,a,b);c||Ed()}function sd(){"undefined"!=typeof SDL&&(v[SDL.screen>>2]=y[SDL.screen>>2]|8388608);td(g.canvas);Ed()}function ud(){"undefined"!=typeof SDL&&(v[SDL.screen>>2]=y[SDL.screen>>2]&-8388609);td(g.canvas);Ed()}
function td(a,b,c){b&&c?(a.Nc=b,a.Ec=c):(b=a.Nc,c=a.Ec);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}N?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ib={},Qc,hd,O,Gd={},Id=()=>{if(!Hd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Gd)void 0===Gd[b]?delete a[b]:a[b]=Gd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Hd=c}return Hd},Hd,Jd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=
(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},Kd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Ld=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))};
function Md(a){var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");return(a.getSupportedExtensions()||
[]).filter(c=>b.includes(c))}var Nd=1,Od=[],P=[],Pd=[],Q=[],Qd=[],nd=[],Rd=[],Sd=[1,1,2,2,4,4,4,2,3,4,8],Td=4;function T(a){Ud||=a}
var Vd=a=>{for(var b=Nd++,c=a.length;c<b;c++)a[c]=null;return b},md=(a,b)=>{a.Hb||(a.Hb=a.getContext,a.getContext=function(d,e){e=a.Hb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Zc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Wd(c,b):0},Wd=(a,b)=>{var c=Vd(nd),d={handle:c,attributes:b,version:b.Zc,ec:a};a.canvas&&(a.canvas.Id=d);nd[c]=d;("undefined"==typeof b.td||b.td)&&Xd(d);d.$c=d.ec.getParameter(34921);d.fc=[];for(a=0;a<d.$c;a++)d.fc[a]={enabled:!1,
wc:!1,size:0,type:0,bd:0,Kc:0,Fb:0,kd:null};d.Ob=[];d.sc=[];d.Ob.length=d.sc.length=22;d.Wb=[];d.cc=[];d.Wb.length=d.cc.length=22;d.Vb=[];d.Vb.length=22;for(a=0;21>=a;++a){d.Vb[a]=null;d.Ob[a]=d.sc[a]=0;d.Wb[a]=[];d.cc[a]=[];b=d.Wb[a];var e=d.cc[a];b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},Xd=a=>{a||=L;if(!a.ud){a.ud=!0;var b=a.ec;Jd(b);Kd(b);Ld(b);b.Sd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Xd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Uc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Uc)b.Uc=b.getExtension("EXT_disjoint_timer_query");b.$d=b.getExtension("WEBGL_multi_draw");Md(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},ld={},Ud,L,Yd,Zd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=M[c](),h=f&&Vd(d);f?(f.name=h,d[h]=f):T(1282);v[b+4*e>>2]=h}};function $d(){var a=Md(M);return a=a.concat(a.map(b=>"GL_"+b))}
var ae=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>L.version){T(1282);return}c=$d().length;break;case 33307:case 33308:if(2>L.version){T(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=M.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T(1280);n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T(1280);n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T(1281)},be=a=>
"]"==a.slice(-1)&&a.lastIndexOf("["),ce=a=>{a-=5120;return 0==a?p:1==a?t:2==a?va:4==a?v:6==a?xa:5==a||28922==a||28520==a||30779==a||30782==a?y:wa},de=a=>{var b=M.sd;if(b){var c=b.dc[a];"number"==typeof c&&(b.dc[a]=c=M.getUniformLocation(b,b.hd[a]+(0<c?`[${c}]`:"")));return c}T(1282)},ee=[];
function fe(a,b,c,d,e,f){this.id=a;this.y=this.x=0;this.kc=!1;this.gd=this.ed=0;this.width=b;this.height=c;this.Cc=d;this.Bc=e;this.Jc=b;this.Ic=c;this.title=f;this.attributes=Object.assign({},ge);this.buttons=0;this.keys=[];this.yc=[];this.Cd=0;this.title=null;this.Rc=this.lc=this.zc=this.dd=this.ic=this.Zb=this.qc=this.ld=this.jc=this.md=0}
var U=null,he=null,V=null,ie=null,ge=null,je=null,ke={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},le=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;
case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;
case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;
case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;
case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;default:return-1}},
me=()=>{var a=U,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},ne=a=>{U&&U.Rc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||O.get(U.Rc)(U.id,a))},oe=(a,b)=>{if(U){var c=le(a);if(-1!=c){var d=b&&U.keys[c];U.keys[c]=b;U.yc[a]=b;U.lc&&(d&&(b=2),O.get(U.lc)(U.id,c,a,b,me()))}}},qe=()=>{pe()},re=()=>{pe()},se=a=>{oe(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},te=a=>{oe(a.keyCode,0)},ue=()=>{if(U)for(var a=0;a<U.yc.length;++a)U.yc[a]&&
oe(a,0)},ve=a=>{if(U){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(je===c.identifier){Bd(c.pageX,c.pageY);b=!0;break}if(!b)return}else Cd(a);a.target==g.canvas&&U.Zb&&U.Zb&&O.get(U.Zb)(U.id,wd,xd)}},xe=a=>{U&&a.target==g.canvas&&U.ic&&O.get(U.ic)(U.id,1)},ye=a=>{U&&a.target==g.canvas&&U.ic&&O.get(U.ic)(U.id,0)},ze=(a,b)=>{if(U&&a.target==g.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();var d=!1;if(null===
je&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],je=d.identifier,Bd(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(je===e.identifier){je=null;d=!0;break}if(!d)return}else Cd(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){U.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else U.buttons&=~(1<<c);U.qc&&O.get(U.qc)(U.id,c,b,me())}},Ae=a=>{U&&ze(a,1)},Be=a=>{U&&ze(a,0)},Ce=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/
3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(U&&U.dd&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;O.get(U.dd)(U.id,b,c);a.preventDefault()}},De=(a,b,c,d)=>{if(U){var e=!1;document.fullscreen||
document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?U.kc||(e=a!=screen.width||b!=screen.height,U.ed=U.x,U.gd=U.y,U.Jc=U.width,U.Ic=U.height,U.x=U.y=0,U.width=screen.width,U.height=screen.height,U.kc=!0):1==U.kc&&(e=a!=U.Jc||b!=U.Ic,U.x=U.ed,U.y=U.gd,U.width=U.Jc,U.height=U.Ic,U.kc=!1);if(e)Fd(U.width,U.height);else if(U.width!=a||U.height!=b||U.Cc!=c||U.Bc!=d)U.width=a,U.height=b,U.Cc=c,U.Bc=d,U&&U.md&&O.get(U.md)(U.id,U.width,U.height),U&&U.jc&&O.get(U.jc)(U.id,U.Cc,U.Bc)}},
Ee={},Fe=[],Ge=null,pe=()=>{if(Xc!==Ge||!Xc){Fe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];Ge=Xc;for(var a=0;a<Fe.length;++a){var b=Fe[a];if(b){Ee[a]||(pa("glfw joystick connected:",a),Ee[a]={id:Fc(b.id),Ld:b.buttons.length,Kd:b.axes.length,buttons:Ec(b.buttons.length),axes:Ec(4*b.axes.length)});for(var c=Ee[a],d=0;d<b.buttons.length;++d)p[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)xa[c.axes+4*d>>2]=b.axes[d]}else Ee[a]&&(pa("glfw joystick disconnected",
a),He(Ee[a].id),He(Ee[a].buttons),He(Ee[a].axes),delete Ee[a])}}},Ie=a=>{function b(l){var m="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=r=>{if(2!=q.readyState)++f,pa("failed to read dropped file: "+l.name+": "+q.error);else{var u=new Uint8Array(r.target.result);r={};r.flags=r.flags||577;var k=Sa(m,r.flags,r.mode);if("string"==typeof u){var x=new Uint8Array(qb(u)+1);u=rb(u,x,0,x.length);pc(k,x,0,u,void 0,r.rd)}else if(ArrayBuffer.isView(u))pc(k,u,0,u.byteLength,
void 0,r.rd);else throw Error("Unsupported data type");Wa(k);if(++f===e){O.get(U.zc)(U.id,e,c);for(r=0;r<d.length;++r)He(d[r]);He(c)}}};q.readAsArrayBuffer(l);var w=Fc(m);d.push(w);y[c+4*h>>2]=w}if(U&&U.zc&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ec(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;rc("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}},Je=a=>{if(U&&U.zc)return a.preventDefault(),
!1};
function Ke(a,b){function c(){ed=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=rd,pd&&d.requestPointerLock(),ed=!0,N?sd():(td(d),Ed())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),N?ud():(td(d),Ed()));if(g.onFullScreen)g.onFullScreen(ed);if(g.onFullscreen)g.onFullscreen(ed)}pd=a;N=b;"undefined"==typeof pd&&(pd=!0);"undefined"==typeof N&&
(N=!1);var d=g.canvas;od||(od=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Le(a,b,c){var d=U&&0<U.attributes[139276]?he:1;b&&c?(a.Nc=b,a.Ec=c):(b=a.Nc,c=a.Ec);var e=b,f=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(e/f<g.forcedAspectRatio?e=Math.round(f*g.forcedAspectRatio):f=Math.round(e/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/e,screen.height/
f);e=Math.round(e*h);f=Math.round(f*h)}N&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}
function Me(a,b){var c=g.canvas.getBoundingClientRect(),d=g.canvas.clientHeight;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=g.canvas.clientWidth/c.width;b*=d/c.height;return{x:a,y:b}}function Ne(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}function Oe(){const a=g.canvas;td(a,a.clientWidth,a.clientHeight);Ed()}
function Pe(){he=Ne();U&&U.ld&&O.get(U.ld)(U.id,he,he);Oe()}
var Qe=[31,29,31,30,31,30,31,31,30,31,30,31],Re=[31,28,31,30,31,30,31,31,30,31,30,31],Se=(a,b,c,d)=>{function e(k,x,z){for(k="number"==typeof k?k.toString():k||"";k.length<x;)k=z[0]+k;return k}function f(k,x){return e(k,x,"0")}function h(k,x){function z(S){return 0>S?-1:0<S?1:0}var F;0===(F=z(k.getFullYear()-x.getFullYear()))&&0===(F=z(k.getMonth()-x.getMonth()))&&(F=z(k.getDate()-x.getDate()));return F}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;
case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var x=k.Qb;for(k=new Date((new Date(k.Rb+1900,0,1)).getTime());0<x;){var z=k.getMonth(),F=(Ac(k.getFullYear())?Qe:Re)[z];if(x>F-k.getDate())x-=F-k.getDate()+1,k.setDate(1),11>z?k.setMonth(z+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+
x);break}}z=new Date(k.getFullYear()+1,0,4);x=l(new Date(k.getFullYear(),0,4));z=l(z);return 0>=h(x,k)?0>=h(z,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=y[d+40>>2];d={Fd:v[d>>2],Ed:v[d+4>>2],tc:v[d+8>>2],Lc:v[d+12>>2],uc:v[d+16>>2],Rb:v[d+20>>2],Lb:v[d+24>>2],Qb:v[d+28>>2],ee:v[d+32>>2],Dd:v[d+36>>2],Gd:q?q?C(t,q):"":""};c=c?C(t,c):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S",
"%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var w in q)c=c.replace(new RegExp(w,"g"),q[w]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),u="January February March April May June July August September October November December".split(" ");q={"%a":k=>r[k.Lb].substring(0,3),"%A":k=>r[k.Lb],"%b":k=>
u[k.uc].substring(0,3),"%B":k=>u[k.uc],"%C":k=>f((k.Rb+1900)/100|0,2),"%d":k=>f(k.Lc,2),"%e":k=>e(k.Lc,2," "),"%g":k=>m(k).toString().substring(2),"%G":m,"%H":k=>f(k.tc,2),"%I":k=>{k=k.tc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var x=0,z=0;z<=k.uc-1;x+=(Ac(k.Rb+1900)?Qe:Re)[z++]);return f(k.Lc+x,3)},"%m":k=>f(k.uc+1,2),"%M":k=>f(k.Ed,2),"%n":()=>"\n","%p":k=>0<=k.tc&&12>k.tc?"AM":"PM","%S":k=>f(k.Fd,2),"%t":()=>"\t","%u":k=>k.Lb||7,"%U":k=>f(Math.floor((k.Qb+7-k.Lb)/7),2),"%V":k=>{var x=
Math.floor((k.Qb+7-(k.Lb+6)%7)/7);2>=(k.Lb+371-k.Qb-2)%7&&x++;if(x)53==x&&(z=(k.Lb+371-k.Qb)%7,4==z||3==z&&Ac(k.Rb)||(x=1));else{x=52;var z=(k.Lb+7-k.Qb-1)%7;(4==z||5==z&&Ac(k.Rb%400-1))&&x++}return f(x,2)},"%w":k=>k.Lb,"%W":k=>f(Math.floor((k.Qb+7-(k.Lb+6)%7)/7),2),"%y":k=>(k.Rb+1900).toString().substring(2),"%Y":k=>k.Rb+1900,"%z":k=>{k=k.Dd;var x=0<=k;k=Math.abs(k)/60;return(x?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.Gd,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(w in q)c.includes(w)&&
(c=c.replace(new RegExp(w,"g"),q[w](d)));c=c.replace(/\0\0/g,"%");w=sb(c,!1);if(w.length>b)return 0;p.set(w,a);return w.length-1};function Zb(a,b,c,d){a||=this;this.parent=a;this.Mb=a.Mb;this.Tb=null;this.id=Rb++;this.name=b;this.mode=c;this.Bb={};this.Db={};this.rdev=d}
Object.defineProperties(Zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ad:{get:function(){return G(this.mode)}},zd:{get:function(){return 8192===(this.mode&61440)}}});[44].forEach(a=>{Eb[a]=new D(a);Eb[a].stack="<generic error, no stack>"});Sb=Array(4096);fc(E,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");vb(259,{read:()=>0,write:(d,e,f,h)=>h});hc("/dev/null",259);ub(1280,xb);ub(1536,yb);hc("/dev/tty",1280);hc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=lb(a).byteLength);return a[--b]};tc("/dev","random",c);tc("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");fc({Mb(){var b=Db(a,"fd",16895,73);b.Bb={lookup(c,d){var e=I(+d);c={parent:null,Mb:{ad:"fake"},Bb:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=rc;g.FS_createDataFile=Lb;g.FS_createPreloadedFile=Mb;g.FS_unlink=kc;g.FS_createLazyFile=vc;g.FS_createDevice=tc;g.requestFullscreen=qd;g.requestAnimationFrame=Pc;g.setCanvasSize=Fd;g.pauseMainLoop=dd;
g.resumeMainLoop=function(){Tc++;var a=Hc,b=Ic,c=Jc;Jc=null;$c(c,0,!1,Sc,!0);Rc(a,b);Lc()};g.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=kd;for(var M,Te=new Float32Array(288),Ue=0;288>Ue;++Ue)ee[Ue]=Te.subarray(0,Ue+1);
var qf={q:a=>{a=new cb(a);0==p[a.Fb+12>>0]&&(p[a.Fb+12>>0]=1,ab--);p[a.Fb+13>>0]=0;$a.push(a);Ve(a.$b);if(We(y[a.Fb+4>>2]))a=y[a.$b>>2];else{var b=y[a.Fb+16>>2];a=0!==b?b:a.$b}return a},t:()=>{W(0,0);var a=$a.pop();Xe(a.$b);bb=0},b:()=>fb([]),m:a=>fb([a]),L:(a,b,c,d)=>fb([a,b,c,d]),na:()=>{var a=$a.pop();a||ra("no exception to throw");var b=a.$b;0==p[a.Fb+13>>0]&&($a.push(a),p[a.Fb+13>>0]=1,p[a.Fb+12>>0]=0,ab++);bb=b;throw bb;},a:(a,b,c)=>{var d=new cb(a);y[d.Fb+16>>2]=0;y[d.Fb+4>>2]=b;y[d.Fb+8>>
2]=c;bb=a;ab++;throw bb;},d:a=>{bb||=a;throw bb;},ja:function(a){try{a=a?C(t,a):"";var b=H(a,{ac:!0});if(null===b.node)throw new D(44);if(!G(b.node.mode))throw new D(54);var c=Yb(b.node,"x");if(c)throw new D(c);nb=b.path;return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Eb}},C:function(a,b,c){yc=c;try{var d=I(a);switch(b){case 0:var e=zc();if(0>e)break;for(;Qb[e];)e++;return dc(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=zc(),d.flags|=e,0;
case 12:return e=zc(),va[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Eb}},fa:function(a,b){try{var c=I(a);return xc(Ta,c.path,b)}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Eb}},ba:function(a,b){try{if(0===b)return-28;var c=nb,d=qb(c)+1;if(b<d)return-68;rb(c,t,a,b);return d}catch(e){if("undefined"==typeof K||"ErrnoError"!==e.name)throw e;return-e.Eb}},ka:function(a,b,c){yc=c;try{var d=I(a);switch(b){case 21509:return d.tty?
0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Nb.wd){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=zc();v[e>>2]=25856;v[e+4>>2]=5;v[e+8>>2]=191;v[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Nb.xd)for(e=zc(),a=[],f=0;32>f;f++)a.push(p[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=zc();return v[e>>2]=0;case 21520:return d.tty?
-28:-59;case 21531:e=zc();if(!d.Db.vd)throw new D(59);return d.Db.vd(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Nb.yd&&(f=[24,80],e=zc(),va[e>>1]=f[0],va[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof K||"ErrnoError"!==h.name)throw h;return-h.Eb}},ca:function(a,b){try{return a=a?C(t,a):"",xc(lc,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.Eb}},fb:function(a,b,c){try{return b=b?
C(t,b):"",b=wc(a,b),b=hb(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),J(b,c),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Eb}},da:function(a,b,c,d){try{b=b?C(t,b):"";var e=d&256;b=wc(a,b,d&4096);return xc(e?lc:Ta,b,c)}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Eb}},I:function(a,b,c,d){yc=d;try{b=b?C(t,b):"";b=wc(a,b);var e=d?zc():0;return Sa(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Eb}},
eb:function(a,b,c,d){try{b=b?C(t,b):"";b=wc(a,b);if(0>=d)return-28;var e=Ub(b),f=Math.min(d,qb(e)),h=p[c+f];rb(e,t,c,d+1);p[c+f]=h;return f}catch(l){if("undefined"==typeof K||"ErrnoError"!==l.name)throw l;return-l.Eb}},cb:function(a){try{return a=a?C(t,a):"",jc(a),0}catch(b){if("undefined"==typeof K||"ErrnoError"!==b.name)throw b;return-b.Eb}},ea:function(a,b){try{return a=a?C(t,a):"",xc(Ta,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.Eb}},db:function(a,b,c){try{return b=
b?C(t,b):"",b=wc(a,b),0===c?kc(b):512===c?jc(b):ra("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Eb}},ga:()=>1,$a:()=>{throw Infinity;},Ua:function(a,b,c){a=new Date(1E3*Dc(a,b));v[c>>2]=a.getSeconds();v[c+4>>2]=a.getMinutes();v[c+8>>2]=a.getHours();v[c+12>>2]=a.getDate();v[c+16>>2]=a.getMonth();v[c+20>>2]=a.getFullYear()-1900;v[c+24>>2]=a.getDay();v[c+28>>2]=(Ac(a.getFullYear())?Bc:Cc)[a.getMonth()]+a.getDate()-1|0;v[c+36>>2]=-(60*
a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();v[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Sa:function(a,b,c,d,e,f,h,l){e=Dc(e,f);try{if(isNaN(e))return 61;var m=I(d);if(0!==(b&2)&&0===(c&2)&&2!==(m.flags&2097155))throw new D(2);if(1===(m.flags&2097155))throw new D(2);if(!m.Db.bc)throw new D(43);var q=m.Db.bc(m,a,e,b,c);var w=q.Fb;v[h>>2]=q.Pc;y[l>>2]=w;return 0}catch(r){if("undefined"==typeof K||
"ErrnoError"!==r.name)throw r;return-r.Eb}},Ta:function(a,b,c,d,e,f,h){f=Dc(f,h);try{if(isNaN(f))return 61;var l=I(e);if(c&2){if(32768!==(l.node.mode&61440))throw new D(43);if(!(d&2)){var m=t.slice(a,a+b);l.Db.rc&&l.Db.rc(l,m,f,b,d)}}}catch(q){if("undefined"==typeof K||"ErrnoError"!==q.name)throw q;return-q.Eb}},bb:(a,b,c)=>{function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=
h.getTimezoneOffset();y[a>>2]=60*Math.max(e,l);v[b>>2]=Number(e!=l);a=d(f);b=d(h);a=Fc(a);b=Fc(b);l<e?(y[c>>2]=a,y[c+4>>2]=b):(y[c>>2]=b,y[c+4>>2]=a)},p:()=>{ra("")},Na:(a,b,c)=>{Gc.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Gc.push(112==d?y[c>>2]:105==d?v[c>>2]:ya[c>>3]);c+=e?8:4}return Xa[a].apply(null,Gc)},x:()=>{dd();Jc=null},ha:()=>Date.now(),A:Nc,ab:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=
Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-sa.buffer.byteLength+65535)/65536;try{sa.grow(e);za();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},z:(a,b,c)=>{a=O.get(a);$c(a,b,c)},hb:(a,b)=>{var c=0;Id().forEach((d,e)=>{var f=b+c;e=y[a+4*e>>2]=f;for(f=0;f<d.length;++f)p[e++>>0]=d.charCodeAt(f);p[e>>0]=0;c+=d.length+1});return 0},aa:(a,b)=>{var c=Id();y[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);y[b>>2]=d;return 0},o:bd,B:function(a){try{var b=I(a);
Wa(b);return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.Eb}},gb:function(a,b){try{var c=I(a);p[b>>0]=c.tty?2:G(c.mode)?3:40960===(c.mode&61440)?7:4;va[b+2>>1]=0;B=[0,(A=0,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+8>>2]=B[0];v[b+12>>2]=B[1];B=[0,(A=0,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+16>>2]=B[0];v[b+20>>2]=B[1];return 0}catch(d){if("undefined"==
typeof K||"ErrnoError"!==d.name)throw d;return d.Eb}},K:function(a,b,c,d){try{a:{var e=I(a);a=b;for(var f,h=b=0;h<c;h++){var l=y[a>>2],m=y[a+4>>2];a+=8;var q=Va(e,p,l,m,f);if(0>q){var w=-1;break a}b+=q;if(q<m)break;"undefined"!==typeof f&&(f+=q)}w=b}y[d>>2]=w;return 0}catch(r){if("undefined"==typeof K||"ErrnoError"!==r.name)throw r;return r.Eb}},Va:function(a,b,c,d,e){b=Dc(b,c);try{if(isNaN(b))return 61;var f=I(a);oc(f,b,d);B=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>
0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[e>>2]=B[0];v[e+4>>2]=B[1];f.Dc&&0===b&&0===d&&(f.Dc=null);return 0}catch(h){if("undefined"==typeof K||"ErrnoError"!==h.name)throw h;return h.Eb}},J:function(a,b,c,d){try{a:{var e=I(a);a=b;for(var f,h=b=0;h<c;h++){var l=y[a>>2],m=y[a+4>>2];a+=8;var q=pc(e,p,l,m,f);if(0>q){var w=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}w=b}y[d>>2]=w;return 0}catch(r){if("undefined"==typeof K||"ErrnoError"!==r.name)throw r;return r.Eb}},W:function(a){M.activeTexture(a)},
_:(a,b)=>{M.attachShader(P[a],Q[b])},S:(a,b)=>{34962==a?M.hc=b:34963==a&&(M.Yb=b);35051==a?M.Tc=b:35052==a&&(M.xc=b);M.bindBuffer(a,Od[b])},V:(a,b)=>{M.bindTexture(a,Pd[b])},Ba:a=>{M.bindVertexArray(Qd[a]);a=M.getParameter(34965);M.Yb=a?a.name|0:0},ta:function(a,b){M.blendFunc(a,b)},s:(a,b,c,d)=>{2<=L.version?c&&b?M.bufferData(a,t,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?t.subarray(c,c+b):b,d)},ya:function(a){M.clear(a)},za:function(a,b,c,d){M.clearColor(a,b,c,d)},Za:a=>{M.compileShader(Q[a])},
Qa:()=>{var a=Vd(P),b=M.createProgram();b.name=a;b.oc=b.mc=b.nc=0;b.Mc=1;P[a]=b;return a},ia:a=>{var b=Vd(Q);Q[b]=M.createShader(a);return b},Aa:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Od[d];e&&(M.deleteBuffer(e),e.name=0,Od[d]=null,d==M.hc&&(M.hc=0),d==M.Yb&&(M.Yb=0),d==M.Tc&&(M.Tc=0),d==M.xc&&(M.xc=0))}},La:a=>{if(a){var b=P[a];b?(M.deleteProgram(b),b.name=0,P[a]=null):T(1281)}},H:a=>{if(a){var b=Q[a];b?(M.deleteShader(b),Q[a]=null):T(1281)}},U:a=>{if(a){var b=Rd[a];b?(M.deleteSync(b),
b.name=0,Rd[a]=null):T(1281)}},Da:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Pd[d];e&&(M.deleteTexture(e),e.name=0,Pd[d]=null)}},sa:function(a){M.depthFunc(a)},G:(a,b,c,d)=>{if(!M.Yb){var e=1*Sd[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var h=L.Vb[f];h?f=h:(h=M.getParameter(34965),L.Vb[f]=M.createBuffer(),M.bindBuffer(34963,L.Vb[f]),M.bufferData(34963,1<<f,35048),M.bindBuffer(34963,h),f=L.Vb[f]);M.bindBuffer(34963,f);M.bufferSubData(34963,0,t.subarray(d,d+e));d=0}Yd=!1;for(e=0;e<L.$c;++e)if(f=
L.fc[e],f.wc&&f.enabled){Yd=!0;h=f.Kc;h=0<h?b*h:f.size*Sd[f.type-5120]*b;var l=32-Math.clz32(0===h?0:h-1);var m=L.Wb[l],q=L.Ob[l];L.Ob[l]=L.Ob[l]+1&63;var w=m[q];w?l=w:(w=M.getParameter(34964),m[q]=M.createBuffer(),M.bindBuffer(34962,m[q]),M.bufferData(34962,1<<l,35048),M.bindBuffer(34962,w),l=m[q]);M.bindBuffer(34962,l);M.bufferSubData(34962,0,t.subarray(f.Fb,f.Fb+h));f.kd.call(M,e,f.size,f.type,f.bd,f.Kc,0)}M.drawElements(a,b,c,d);Yd&&M.bindBuffer(34962,Od[M.hc]);M.Yb||M.bindBuffer(34963,null)},
F:function(a){M.enable(a)},w:a=>{L.fc[a].enabled=!0;M.enableVertexAttribArray(a)},Ea:(a,b)=>(a=M.fenceSync(a,b))?(b=Vd(Rd),a.name=b,Rd[b]=a,b):0,T:(a,b)=>{Zd(a,b,"createBuffer",Od)},Fa:(a,b)=>{Zd(a,b,"createTexture",Pd)},Ca:function(a,b){Zd(a,b,"createVertexArray",Qd)},Ga:(a,b)=>ae(a,b),Ma:(a,b,c,d)=>{a=M.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?rb(a,t,d,b):0;c&&(v[c>>2]=b)},Z:(a,b,c)=>{if(c)if(a>=Nd)T(1281);else if(a=P[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
v[c>>2]=a.length+1;else if(35719==b){if(!a.oc)for(b=0;b<M.getProgramParameter(a,35718);++b)a.oc=Math.max(a.oc,M.getActiveUniform(a,b).name.length+1);v[c>>2]=a.oc}else if(35722==b){if(!a.mc)for(b=0;b<M.getProgramParameter(a,35721);++b)a.mc=Math.max(a.mc,M.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.mc}else if(35381==b){if(!a.nc)for(b=0;b<M.getProgramParameter(a,35382);++b)a.nc=Math.max(a.nc,M.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.nc}else v[c>>2]=M.getProgramParameter(a,b);else T(1281)},
Ra:(a,b,c,d)=>{a=M.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?rb(a,t,d,b):0;c&&(v[c>>2]=b)},$:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=M.getShaderParameter(Q[a],b):T(1281)},Ja:(a,b)=>{b=b?C(t,b):"";if(a=P[a]){var c=a,d=c.dc,e=c.jd,f;if(!d)for(c.dc=d={},c.hd={},f=0;f<M.getProgramParameter(c,35718);++f){var h=M.getActiveUniform(c,f);var l=h.name;h=
h.size;var m=be(l);m=0<m?l.slice(0,m):l;var q=c.Mc;c.Mc+=h;e[m]=[h,q];for(l=0;l<h;++l)d[q]=l,c.hd[q++]=m}c=a.dc;d=0;e=b;f=be(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.jd[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else T(1281);return-1},Pa:a=>{a=P[a];M.linkProgram(a);a.dc=0;a.jd={}},Y:(a,b)=>{3317==a&&(Td=b);M.pixelStorei(a,b)},ib:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var h=(h=y[c+4*f>>2])?C(t,h,d?y[d+4*f>>2]:void 0):"";e+=h}M.shaderSource(Q[a],e)},X:(a,
b,c,d,e,f,h,l,m)=>{if(2<=L.version)if(M.xc)M.texImage2D(a,b,c,d,e,f,h,l,m);else if(m){var q=ce(l);M.texImage2D(a,b,c,d,e,f,h,l,q,m>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else M.texImage2D(a,b,c,d,e,f,h,l,null);else{q=M;var w=q.texImage2D;if(m){var r=ce(l),u=31-Math.clz32(r.BYTES_PER_ELEMENT),k=Td;m=r.subarray(m>>u,m+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[h-6402]||1)*(1<<u)+k-1&-k)>>u)}else m=null;w.call(q,a,b,c,d,e,f,h,l,m)}},y:function(a,b,c){M.texParameteri(a,b,c)},Ia:(a,
b)=>{M.uniform1i(de(a),b)},Ha:(a,b,c,d)=>{if(2<=L.version)b&&M.uniformMatrix4fv(de(a),!!c,xa,d>>2,16*b);else{if(18>=b){var e=ee[16*b-1],f=xa;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=xa.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(de(a),!!c,e)}},Ka:a=>{a=P[a];M.useProgram(a);
M.sd=a},Oa:a=>{M.validateProgram(P[a])},v:(a,b,c,d,e,f)=>{var h=L.fc[a];M.hc?(h.wc=!1,M.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.bd=d,h.Kc=e,h.Fb=f,h.wc=!0,h.kd=function(l,m,q,w,r,u){this.vertexAttribPointer(l,m,q,w,r,u)})},O:function(a,b,c,d){M.viewport(a,b,c,d)},Ya:(a,b,c,d)=>{M.waitSync(Rd[a],b,(c>>>0)+4294967296*d)},wa:(a,b,c,d)=>{var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?
qd():Fd(a,b);for(e=0;e<V.length&&null==V[e];e++);a=0<ge[139265];e==V.length&&(a?g.Xb=kd(g.canvas,!0,!0,{antialias:1<ge[135181],depth:0<ge[135173],stencil:0<ge[135174],alpha:0<ge[135172]}):Jb());!g.Xb&&a?f=0:(e=g.canvas,c=new fe(f,e.clientWidth,e.clientHeight,e.width,e.height,c),f-1==V.length?V.push(c):V[f-1]=c,U=c,Oe(),f=c.id)}return f},pa:(a,b,c)=>{var d=0,e=0;if(a=0>=a||!V?null:V[a-1])d=a.width,e=a.height;b&&(v[b>>2]=d);c&&(v[c>>2]=e)},xa:()=>{if(V)return 1;Nc();ge=Object.assign({},ke);V=[];U=null;
he=Ne();window.addEventListener("gamepadconnected",qe,!0);window.addEventListener("gamepaddisconnected",re,!0);window.addEventListener("keydown",se,!0);window.addEventListener("keypress",ne,!0);window.addEventListener("keyup",te,!0);window.addEventListener("blur",ue,!0);ie=window.matchMedia("(resolution: "+Ne()+"dppx)");ie.addEventListener("change",Pe);g.canvas.addEventListener("touchmove",ve,!0);g.canvas.addEventListener("touchstart",Ae,!0);g.canvas.addEventListener("touchcancel",Be,!0);g.canvas.addEventListener("touchend",
Be,!0);g.canvas.addEventListener("mousemove",ve,!0);g.canvas.addEventListener("mousedown",Ae,!0);g.canvas.addEventListener("mouseup",Be,!0);g.canvas.addEventListener("wheel",Ce,!0);g.canvas.addEventListener("mousewheel",Ce,!0);g.canvas.addEventListener("mouseenter",xe,!0);g.canvas.addEventListener("mouseleave",ye,!0);g.canvas.addEventListener("drop",Ie,!0);g.canvas.addEventListener("dragover",Je,!0);qd=Ke;Ad=Me;td=Le;Dd.push((a,b)=>{if(U&&0<U.attributes[139276]){var c=g.canvas;De(c.clientWidth,c.clientHeight,
a,b)}else De(a,b,a,b)});return 1},va:()=>{},oa:()=>{},R:(a,b)=>{if(a=0>=a||!V?null:V[a-1]){var c=a.Zb;a.Zb=b;b=c}else b=null;return b},ua:(a,b)=>{a=0>=a||!V?null:V[a-1];if(!a)return null;var c=a.jc;a.jc=b;return c},P:(a,b)=>{if(a=0>=a||!V?null:V[a-1]){var c=a.lc;a.lc=b;b=c}else b=null;return b},Q:(a,b)=>{if(a=0>=a||!V?null:V[a-1]){var c=a.qc;a.qc=b;b=c}else b=null;return b},qa:()=>{},N:(a,b)=>{ge[a]=b},ra:a=>(a=0>=a||!V?null:V[a-1])?a.Cd:0,e:Ye,M:Ze,f:$e,c:af,n:bf,u:cf,la:df,ma:ef,D:ff,Xa:gf,l:hf,
h:jf,g:kf,i:lf,j:mf,E:nf,k:of,Wa:pf,r:a=>a,_a:(a,b,c,d)=>Se(a,b,c,d)},X=function(){function a(c){X=c.exports;sa=X.jb;za();O=X.mb;Ca.unshift(X.kb);Ka("wasm-instantiate");return X}var b={a:qf};Ja("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ra(b,function(c){a(c.instance)});return{}}(),rf=g._main=(a,b)=>(rf=g._main=X.lb)(a,b),Ec=a=>(Ec=X.nb)(a),He=a=>(He=X.ob)(a),db=a=>(db=X.pb)(a),zb=(a,b)=>
(zb=X.qb)(a,b),W=(a,b)=>(W=X.rb)(a,b),Y=()=>(Y=X.sb)(),Z=a=>(Z=X.tb)(a),sf=a=>(sf=X.ub)(a),Xe=a=>(Xe=X.vb)(a),Ve=a=>(Ve=X.wb)(a),eb=(a,b,c)=>(eb=X.xb)(a,b,c),We=a=>(We=X.yb)(a),tf=g.dynCall_iij=(a,b,c,d)=>(tf=g.dynCall_iij=X.zb)(a,b,c,d),uf=g.dynCall_vij=(a,b,c,d)=>(uf=g.dynCall_vij=X.Ab)(a,b,c,d);function lf(a,b,c,d){var e=Y();try{O.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function $e(a,b,c){var d=Y();try{return O.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}
function af(a,b,c,d){var e=Y();try{return O.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Ye(a,b){var c=Y();try{return O.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function kf(a,b,c){var d=Y();try{O.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function jf(a,b){var c=Y();try{O.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function nf(a,b,c,d,e,f){var h=Y();try{O.get(a)(b,c,d,e,f)}catch(l){Z(h);if(l!==l+0)throw l;W(1,0)}}
function cf(a,b,c,d,e,f){var h=Y();try{return O.get(a)(b,c,d,e,f)}catch(l){Z(h);if(l!==l+0)throw l;W(1,0)}}function of(a,b,c,d,e,f,h){var l=Y();try{O.get(a)(b,c,d,e,f,h)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function mf(a,b,c,d,e){var f=Y();try{O.get(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}function bf(a,b,c,d,e){var f=Y();try{return O.get(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}
function ff(a,b,c,d,e,f,h,l,m,q){var w=Y();try{return O.get(a)(b,c,d,e,f,h,l,m,q)}catch(r){Z(w);if(r!==r+0)throw r;W(1,0)}}function hf(a){var b=Y();try{O.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function Ze(a,b,c){var d=Y();try{return O.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function ef(a,b,c,d,e,f,h,l,m){var q=Y();try{return O.get(a)(b,c,d,e,f,h,l,m)}catch(w){Z(q);if(w!==w+0)throw w;W(1,0)}}
function df(a,b,c,d,e,f,h){var l=Y();try{return O.get(a)(b,c,d,e,f,h)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function gf(a,b,c,d){var e=Y();try{return tf(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function pf(a,b,c,d){var e=Y();try{uf(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}g.addRunDependency=Ja;g.removeRunDependency=Ka;g.FS_createPath=rc;g.FS_createLazyFile=vc;g.FS_createDevice=tc;g.FS_createPreloadedFile=Mb;g.FS_createDataFile=Lb;g.FS_unlink=kc;var vf;
Ia=function wf(){vf||xf();vf||(Ia=wf)};function yf(a=[]){var b=rf;a.unshift(ca);var c=a.length,d=sf(4*(c+1)),e=d;a.forEach(h=>{var l=y,m=e>>2,q=qb(h)+1,w=sf(q);rb(h,t,w,q);l[m]=w;e+=4});y[e>>2]=0;try{var f=b(c,d);bd(f,!0)}catch(h){Zc(h)}}
function xf(){var a=ba;function b(){if(!vf&&(vf=!0,g.calledRun=!0,!ta)){g.noFSInit||qc||(qc=!0,g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?tc("/dev","stdin",g.stdin):ic("/dev/tty","/dev/stdin"),g.stdout?tc("/dev","stdout",null,g.stdout):ic("/dev/tty","/dev/stdout"),g.stderr?tc("/dev","stderr",null,g.stderr):ic("/dev/tty1","/dev/stderr"),Sa("/dev/stdin",0),Sa("/dev/stdout",1),Sa("/dev/stderr",1));Tb=!1;Ya(Ca);Ya(Da);if(g.onRuntimeInitialized)g.onRuntimeInitialized();zf&&yf(a);if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Ea.unshift(c)}Ya(Ea)}}if(!(0<Ga)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Fa();Ya(Aa);0<Ga||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var zf=!0;g.noInitialRun&&(zf=!1);xf();
