var g;g||=typeof Module !== 'undefined' ? Module : {};g.Yb||(g.Yb=0);g.Yb++;
g.ENVIRONMENT_IS_PTHREAD||g.$ww||function(a){function b(m,r,p,u){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(m,function(k,x){k?u(k):p(x.buffer)});else{var w=new XMLHttpRequest;w.open("GET",m,!0);w.responseType="arraybuffer";w.onprogress=function(k){var x=r;k.total&&(x=k.total);if(k.loaded){w.ib?g.wb[m].loaded=k.loaded:(w.ib=!0,g.wb||(g.wb={}),g.wb[m]={loaded:k.loaded,total:x});var z=x=k=0,G;for(G in g.wb){var P=g.wb[G];
k+=P.total;x+=P.loaded;z++}k=Math.ceil(k*g.Yb/z);g.setStatus&&g.setStatus(`Downloading data... (${x}/${k})`)}else!g.wb&&g.setStatus&&g.setStatus("Downloading data...")};w.onerror=function(){throw Error("NetworkError for: "+m);};w.onload=function(){if(200==w.status||304==w.status||206==w.status||0==w.status&&w.response)p(w.response);else throw Error(w.statusText+" : "+w.responseURL);};w.send(null)}}function c(m){console.error("package error:",m)}function d(){function m(w,k,x){this.start=w;this.end=
k;this.audio=x}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(w.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);m.prototype.ac=w;w=a.files;for(var k=0;k<w.length;++k)m.prototype.ib[w[k].filename].onload();g.removeRunDependency("datafile_Test/Test.data")}g.FS_createPath("/","assets",!0,!0);m.prototype={ib:{},open:function(w,k){this.name=k;this.ib[k]=this;g.addRunDependency(`fp ${this.name}`)},send:function(){},onload:function(){this.xb(this.ac.subarray(this.start,
this.end))},xb:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency(`fp ${this.name}`);this.ib[this.name]=null}};for(var p=a.files,u=0;u<p.length;++u)(new m(p[u].start,p[u].end,p[u].audio||0)).open("GET",p[u].filename);g.addRunDependency("datafile_Test/Test.data");g.Bc||(g.Bc={});g.Bc["Test/Test.data"]={Gd:!1};l?(r(l),l=null):h=r}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,n("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("Test.data",""):"Test.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?
g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))}({files:[{filename:"/assets/cube.obj",start:0,end:1209},{filename:"/assets/teapot.obj",start:1209,end:541789},{filename:"/assets/text.txt",start:541789,end:541789}],remote_package_size:541789});
var aa=Object.assign({},g),ca=[],da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",ja,ka,la;
if(ia){var fs=require("fs"),ma=require("path");q=ha?ma.dirname(q)+"/":__dirname+"/";ja=(a,b)=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a};ka=(a,b,c,d=!0)=>{a=na(a)?new URL(a):ma.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!g.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);
process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;});ea=(a,b)=>{process.exitCode=a;throw b;};g.inspect=()=>"[Emscripten Module object]"}else if(fa||ha)ha?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=
new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=g.print||console.log.bind(console),n=g.printErr||console.error.bind(console);Object.assign(g,aa);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);var qa;
g.wasmBinary&&(qa=g.wasmBinary);"object"!=typeof WebAssembly&&t("no native wasm support detected");var ra,sa=!1,ta,v,y,ua,A,B,va;function wa(){var a=ra.buffer;g.HEAP8=v=new Int8Array(a);g.HEAP16=ua=new Int16Array(a);g.HEAPU8=y=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAP32=A=new Int32Array(a);g.HEAPU32=B=new Uint32Array(a);g.HEAPF32=va=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var xa=[],ya=[],za=[],Aa=[];function Ba(){var a=g.preRun.shift();xa.unshift(a)}var Ca=0,Da=null,Ea=null;
function Fa(){Ca++;g.monitorRunDependencies&&g.monitorRunDependencies(Ca)}function Ga(){Ca--;g.monitorRunDependencies&&g.monitorRunDependencies(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function t(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";n(a);sa=!0;ta=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ha=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ia;Ia="Test.wasm";
if(!Ha(Ia)){var Ja=Ia;Ia=g.locateFile?g.locateFile(Ja,q):q+Ja}function Ka(a){if(a==Ia&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function La(a){if(!qa&&(fa||ha)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ka(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{n(`failed to asynchronously prepare wasm: ${d}`);t(d)})}
function Na(a,b){var c=Ia;qa||"function"!=typeof WebAssembly.instantiateStreaming||Ha(c)||na(c)||ia||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){n(`wasm streaming compile failed: ${e}`);n("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}var C,D;function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Oa=a=>{for(;0<a.length;)a.shift()(g)},Pa=g.noExitRuntime||!0,Qa=[],Ra=0,Sa=0;
function Ta(a){this.Eb=a;this.lb=a-24;this.hd=function(b){B[this.lb+4>>2]=b};this.ib=function(){return B[this.lb+4>>2]};this.gd=function(b){B[this.lb+8>>2]=b};this.Dc=function(b){v[this.lb+12>>0]=b?1:0};this.Wc=function(){return 0!=v[this.lb+12>>0]};this.Ec=function(b){v[this.lb+13>>0]=b?1:0};this.Uc=function(){return 0!=v[this.lb+13>>0]};this.ed=function(b,c){this.xb(0);this.hd(b);this.gd(c)};this.xb=function(b){B[this.lb+16>>2]=b};this.ac=function(){return B[this.lb+16>>2]};this.dd=function(){if(Ua(this.ib()))return B[this.Eb>>
2];var b=this.ac();return 0!==b?b:this.Eb}}
var Xa=a=>{var b=Sa;if(!b)return Va(0),0;var c=new Ta(b);c.xb(b);var d=c.ib();if(!d)return Va(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Wa(f,d,c.lb+16))return Va(f),b}Va(d);return b},Ya=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},E=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ya(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?
"/":"")+a},Za=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},$a=a=>{if("/"===a)return"/";a=E(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},ab=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;
return c=>(c.set(b(c.byteLength)),c)}catch(c){}t("initRandomDevice")},bb=a=>(bb=ab())(a);function cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:db;if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ya(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var eb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&eb)return eb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
fb=[],gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},hb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&
63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function ib(a,b){var c=Array(gb(a)+1);a=hb(a,c,0,c.length);b&&(c.length=a);return c}var jb=[];function kb(a,b){jb[a]={input:[],output:[],rb:b};lb(a,mb)}
var mb={open(a){var b=jb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close(a){a.tty.rb.fsync(a.tty)},fsync(a){a.tty.rb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.rb.rc)throw new H(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.rb.rc(a.tty)}catch(l){throw new H(29);}if(void 0===h&&0===e)throw new H(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.rb.dc)throw new H(60);try{for(var e=0;e<d;e++)a.tty.rb.dc(a.tty,b[c+
e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},nb={rc(){a:{if(!fb.length){var a=null;if(ia){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}fb=ib(a,!0)}a=
fb.shift()}return a},dc(a,b){null===b||10===b?(pa(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(F(a.output,0)),a.output=[])},Zc(){return{Ad:25856,Cd:5,zd:191,Bd:35387,yd:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},$c(){return 0},ad(){return[24,80]}},ob={dc(a,b){null===b||10===b?(n(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(n(F(a.output,0)),a.output=[])}};
function pb(a,b){var c=a.gb?a.gb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.gb,a.gb=new Uint8Array(b),0<a.jb&&a.gb.set(c.subarray(0,a.jb),0))}
var I={ob:null,qb(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.ob||(I.ob={dir:{node:{nb:I.fb.nb,mb:I.fb.mb,lookup:I.fb.lookup,Qb:I.fb.Qb,rename:I.fb.rename,unlink:I.fb.unlink,rmdir:I.fb.rmdir,readdir:I.fb.readdir,symlink:I.fb.symlink},stream:{tb:I.hb.tb}},file:{node:{nb:I.fb.nb,mb:I.fb.mb},stream:{tb:I.hb.tb,read:I.hb.read,write:I.hb.write,jc:I.hb.jc,cc:I.hb.cc,zc:I.hb.zc}},link:{node:{nb:I.fb.nb,mb:I.fb.mb,readlink:I.fb.readlink},
stream:{}},mc:{node:{nb:I.fb.nb,mb:I.fb.mb},stream:qb}});c=rb(a,b,c,d);J(c.mode)?(c.fb=I.ob.dir.node,c.hb=I.ob.dir.stream,c.gb={}):32768===(c.mode&61440)?(c.fb=I.ob.file.node,c.hb=I.ob.file.stream,c.jb=0,c.gb=null):40960===(c.mode&61440)?(c.fb=I.ob.link.node,c.hb=I.ob.link.stream):8192===(c.mode&61440)&&(c.fb=I.ob.mc.node,c.hb=I.ob.mc.stream);c.timestamp=Date.now();a&&(a.gb[b]=c,a.timestamp=c.timestamp);return c},Id(a){return a.gb?a.gb.subarray?a.gb.subarray(0,a.jb):new Uint8Array(a.gb):new Uint8Array(0)},
fb:{nb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.jb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Qc=4096;b.blocks=Math.ceil(b.size/b.Qc);return b},mb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.jb!=b))if(0==
b)a.gb=null,a.jb=0;else{var c=a.gb;a.gb=new Uint8Array(b);c&&a.gb.set(c.subarray(0,Math.min(b,a.jb)));a.jb=b}},lookup(){throw sb[44];},Qb(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){if(J(a.mode)){try{var d=tb(b,c)}catch(f){}if(d)for(var e in d.gb)throw new H(55);}delete a.parent.gb[a.name];a.parent.timestamp=Date.now();a.name=c;b.gb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.gb[b];a.timestamp=Date.now()},rmdir(a,b){var c=tb(a,b),d;for(d in c.gb)throw new H(55);delete a.gb[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.gb)a.gb.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},hb:{read(a,b,c,d,e){var f=a.node.gb;if(e>=a.node.jb)return 0;a=Math.min(a.node.jb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===v.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.gb||a.gb.subarray)){if(f)return a.gb=b.subarray(c,c+d),a.jb=d;if(0===a.jb&&0===e)return a.gb=b.slice(c,c+d),a.jb=d;if(e+d<=a.jb)return a.gb.set(b.subarray(c,c+d),e),d}pb(a,e+d);if(a.gb.subarray&&b.subarray)a.gb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.gb[e+f]=b[c+f];a.jb=Math.max(a.jb,e+d);return d},tb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.jb);if(0>b)throw new H(28);return b},jc(a,b,c){pb(a.node,b+c);a.node.jb=Math.max(a.node.jb,
b+c)},cc(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.gb;if(e&2||a.buffer!==v.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;t();b=void 0;if(!b)throw new H(48);v.set(a,b)}else c=!1,b=a.byteOffset;return{lb:b,ud:c}},zc(a,b,c,d){I.hb.write(a,b,0,d,c,!1);return 0}}},ub=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{e||t(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});d&&Fa(d)},vb=g.preloadPlugins||[],yb=(a,b,c,d)=>{"undefined"!=typeof wb&&xb();var e=!1;vb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Ab=(a,b,c,d,e,f,h,l,m,r)=>{function p(k){function x(z){r&&r();l||zb(a,b,z,d,e,m);f&&f();Ga(w)}yb(k,u,x,()=>{h&&h();Ga(w)})||x(k)}var u=b?cb(E(a+"/"+b)):a,w=`cp ${u}`;Fa(w);"string"==typeof c?ub(c,k=>p(k),h):p(c)},Bb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Cb=null,Db={},Eb=[],Fb=1,Gb=null,db="/",Hb=!0,H=null,sb={};
function K(a,b={}){a=cb(a);if(!a)return{path:"",node:null};b=Object.assign({qc:!0,ec:0},b);if(8<b.ec)throw new H(32);a=a.split("/").filter(h=>!!h);for(var c=Cb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=tb(c,a[e]);d=E(d+"/"+a[e]);c.yb&&(!f||f&&b.qc)&&(c=c.yb.root);if(!f||b.Fb)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=cb(Za(d),c),c=K(d,{ec:b.ec+1}).node,40<f++)throw new H(32);}return{path:d,node:c}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.qb.xc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Lb(a){var b=Kb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.zb;else for(b=Gb[b];b;){if(b.zb===a){b.zb=a.zb;break}b=b.zb}}
function tb(a,b){var c;if(c=(c=Mb(a,"x"))?c:a.fb.lookup?0:2)throw new H(c,a);for(c=Gb[Kb(a.id,b)];c;c=c.zb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.fb.lookup(a,b)}function rb(a,b,c,d){a=new Nb(a,b,c,d);b=Kb(a.parent.id,a.name);a.zb=Gb[b];return Gb[b]=a}function J(a){return 16384===(a&61440)}function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Mb(a,b){if(Hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Pb(a,b){try{return tb(a,b),20}catch(c){}return Mb(a,"wx")}function Qb(a,b,c){try{var d=tb(a,b)}catch(e){return e.kb}if(a=Mb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(d===d.parent||Jb(d)===db)return 10}else if(J(d.mode))return 31;return 0}function Rb(){for(var a=0;4096>=a;a++)if(!Eb[a])return a;throw new H(33);}
function Sb(a){a=Eb[a];if(!a)throw new H(8);return a}function Tb(a,b=-1){Ub||(Ub=function(){this.ib={}},Ub.prototype={},Object.defineProperties(Ub.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ib.flags},set(c){this.ib.flags=c}},position:{get(){return this.ib.position},set(c){this.ib.position=c}}}));a=Object.assign(new Ub,a);-1==b&&(b=Rb());a.fd=b;return Eb[b]=a}var qb={open(a){a.hb=Db[a.node.rdev].hb;a.hb.open&&a.hb.open(a)},tb(){throw new H(70);}};
function lb(a,b){Db[a]={hb:b}}function Vb(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new H(10);if(!c&&!d){var e=K(b,{qc:!1});b=e.path;e=e.node;if(e.yb)throw new H(10);if(!J(e.mode))throw new H(54);}b={type:a,Pd:{},xc:b,jd:[]};a=a.qb(b);a.qb=b;b.root=a;c?Cb=a:e&&(e.yb=b,e.qb&&e.qb.jd.push(b))}function Wb(a,b,c){var d=K(a,{parent:!0}).node;a=$a(a);if(!a||"."===a||".."===a)throw new H(28);var e=Pb(d,a);if(e)throw new H(e);if(!d.fb.Qb)throw new H(63);return d.fb.Qb(d,a,b,c)}
function L(a,b){return Wb(a,(void 0!==b?b:511)&1023|16384,0)}function Xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Wb(a,b|8192,c)}function Yb(a,b){if(!cb(a))throw new H(44);var c=K(b,{parent:!0}).node;if(!c)throw new H(44);b=$a(b);var d=Pb(c,b);if(d)throw new H(d);if(!c.fb.symlink)throw new H(63);c.fb.symlink(c,b,a)}function Zb(a){var b=K(a,{parent:!0}).node;a=$a(a);var c=tb(b,a),d=Qb(b,a,!0);if(d)throw new H(d);if(!b.fb.rmdir)throw new H(63);if(c.yb)throw new H(10);b.fb.rmdir(b,a);Lb(c)}
function $b(a){var b=K(a,{parent:!0}).node;if(!b)throw new H(44);a=$a(a);var c=tb(b,a),d=Qb(b,a,!1);if(d)throw new H(d);if(!b.fb.unlink)throw new H(63);if(c.yb)throw new H(10);b.fb.unlink(b,a);Lb(c)}function Ib(a){a=K(a).node;if(!a)throw new H(44);if(!a.fb.readlink)throw new H(28);return cb(Jb(a.parent),a.fb.readlink(a))}function ac(a,b){a="string"==typeof a?K(a,{Fb:!0}).node:a;if(!a.fb.mb)throw new H(63);a.fb.mb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function bc(a,b,c){if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=E(a);try{e=K(a,{Fb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Wb(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!J(e.mode))throw new H(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:J(e.mode)&&("r"!==Ob(b)||b&512)?31:Mb(e,Ob(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Fb:!0}).node:c;if(!c.fb.mb)throw new H(63);if(J(c.mode))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=Mb(c,"w"))throw new H(d);c.fb.mb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Tb({node:e,path:Jb(e),flags:b,seekable:!0,position:0,hb:e.hb,rd:[],error:!1});e.hb.open&&e.hb.open(e);!g.logReadFiles||b&1||(cc||={},a in cc||(cc[a]=1));return e}
function dc(a){if(null===a.fd)throw new H(8);a.$b&&(a.$b=null);try{a.hb.close&&a.hb.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null}function ec(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.hb.tb)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.hb.tb(a,b,c);a.rd=[]}
function fc(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(J(a.node.mode))throw new H(31);if(!a.hb.write)throw new H(28);a.seekable&&a.flags&1024&&ec(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H(70);b=a.hb.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function gc(){H||(H=function(a,b){this.name="ErrnoError";this.node=b;this.ld=function(c){this.kb=c};this.ld(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{sb[a]=new H(a);sb[a].stack="<generic error, no stack>"}))}var hc;function ic(a,b){a="string"==typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=E(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}
function jc(a,b,c,d){a=E(("string"==typeof a?a:Jb(a))+"/"+b);c=Bb(c,d);return Wb(a,(void 0!==c?c:438)&4095|32768,0)}function zb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Jb(a),h=b?E(a+"/"+b):a);a=Bb(d,e);h=Wb(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}ac(h,a|146);b=bc(h,577);fc(b,c,0,c.length,0,f);dc(b);ac(h,a)}}
function kc(a,b,c,d){a=E(("string"==typeof a?a:Jb(a))+"/"+b);b=Bb(!!c,!!d);kc.uc||(kc.uc=64);var e=kc.uc++<<8|0;lb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,h,l,m){for(var r=0,p=0;p<m;p++){try{var u=c()}catch(w){throw new H(29);}if(void 0===u&&0===r)throw new H(6);if(null===u||void 0===u)break;r++;h[l+p]=u}r&&(f.node.timestamp=Date.now());return r},write(f,h,l,m){for(var r=0;r<m;r++)try{d(h[l+r])}catch(p){throw new H(29);}m&&(f.node.timestamp=Date.now());return r}});
return Xb(a,b,e)}function lc(a){if(!(a.bd||a.cd||a.link||a.gb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.gb=ib(ja(a.url),!0),a.jb=a.gb.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function mc(a,b,c,d,e){function f(){this.bc=!1;this.ib=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var u=p%this.chunkSize;return this.sc(p/this.chunkSize|0)[u]}};f.prototype.xb=function(p){this.sc=p};f.prototype.kc=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var u=Number(p.getResponseHeader("Content-length")),w,k=(w=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;p=(w=p.getResponseHeader("Content-Encoding"))&&"gzip"===w;var x=1048576;k||(x=u);var z=this;z.xb(G=>{var P=G*x,ba=(G+1)*x-1;ba=Math.min(ba,u-1);if("undefined"==typeof z.ib[G]){var $d=z.ib;if(P>ba)throw Error("invalid range ("+P+", "+ba+") or no bytes requested!");if(ba>u-1)throw Error("only "+u+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);u!==x&&R.setRequestHeader("Range","bytes="+P+"-"+ba);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");
R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);P=void 0!==R.response?new Uint8Array(R.response||[]):ib(R.responseText||"",!0);$d[G]=P}if("undefined"==typeof z.ib[G])throw Error("doXHR failed!");return z.ib[G]});if(p||!u)x=u=1,x=u=this.sc(0).length,pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Pc=u;this.Oc=x;this.bc=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new f;Object.defineProperties(h,{length:{get:function(){this.bc||this.kc();return this.Pc}},chunkSize:{get:function(){this.bc||this.kc();return this.Oc}}});var l=void 0}else l=c,h=void 0;var m=jc(a,b,d,e);h?m.gb=h:l&&(m.gb=null,m.url=l);Object.defineProperties(m,{jb:{get:function(){return this.gb.length}}});var r={};Object.keys(m.hb).forEach(p=>{var u=m.hb[p];r[p]=function(){lc(m);return u.apply(null,arguments)}});r.read=(p,u,w,k,x)=>{lc(m);p=p.node.gb;if(x>=p.length)u=0;else{k=Math.min(p.length-
x,k);if(p.slice)for(var z=0;z<k;z++)u[w+z]=p[x+z];else for(z=0;z<k;z++)u[w+z]=p.get(x+z);u=k}return u};r.cc=()=>{lc(m);t();throw new H(48);};m.hb=r;return m}var M={},Ub,cc;function nc(a,b){if("/"===b.charAt(0))return b;a=-100===a?db:Sb(a).path;if(0==b.length)throw new H(44);return E(a+"/"+b)}var oc=void 0;function pc(){var a=A[+oc>>2];oc+=4;return a}
var qc=a=>0===a%4&&(0!==a%100||0===a%400),rc=[0,31,60,91,121,152,182,213,244,274,305,335],sc=[0,31,59,90,120,151,181,212,243,273,304,334],uc=a=>{var b=gb(a)+1,c=tc(b);c&&hb(a,y,c,b);return c},Fc=(a,b)=>{vc=a;wc=b;if(xc)if(yc||=!0,0==a)zc=function(){var d=Math.max(0,Ac+b-Bc())|0;setTimeout(Cc,d)};else if(1==a)zc=function(){Dc(Cc)};else if(2==a){if("undefined"==typeof Ec)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),
c.shift()()},!0);Ec=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else Ec=setImmediate;zc=function(){Ec(Cc)}}},Bc;Bc=()=>performance.now();
var Oc=(a,b,c,d,e)=>{!xc||t("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");xc=a;Gc=d;var f=Hc;yc=!1;Cc=function(){if(!sa)if(0<Ic.length){var h=Ic.shift();h.Hd(h.vd);if(Jc){var l=Jc,m=0==l%1?l-1:Math.floor(l);Jc=h.Dd?m:(8*l+(m+.5))/9}g.setStatus&&(h=g.statusMessage||"Please wait...",l=Jc,m=Kc.Fd,l?l<m?g.setStatus(h+" ("+(m-l)+"/"+m+")"):g.setStatus(h):g.setStatus(""));
f<Hc||setTimeout(Cc,0)}else if(!(f<Hc))if(Lc=Lc+1|0,1==vc&&1<wc&&0!=Lc%wc)zc();else{0==vc&&(Ac=Bc());if(N)for(h=N.Bb,N.Bb=N.Gb,N.Gb=h,h=N.sb,N.sb=N.Rb,N.Rb=h,h=0;21>=h;++h)N.sb[h]=0;if(!(sa||g.preMainLoop&&!1===g.preMainLoop())){if(!sa)try{a(),Mc()}catch(r){Nc(r)}g.postMainLoop&&g.postMainLoop()}f<Hc||("object"==typeof SDL&&SDL.audio&&SDL.audio.kd&&SDL.audio.kd(),zc())}};e||(b&&0<b?Fc(0,1E3/b):Fc(1,1),zc());if(c)throw"unwind";},Nc=a=>{a instanceof oa||"unwind"==a||ea(1,a)},Pc=a=>{ta=a;if(!Pa){if(g.onExit)g.onExit(a);
sa=!0}ea(a,new oa(a))},Qc=a=>{ta=a;Pc(a)},Mc=()=>{if(!Pa)try{var a=ta;ta=a;Pc(a)}catch(b){Nc(b)}},Rc=a=>{setTimeout(()=>{if(!sa)try{a(),Mc()}catch(b){Nc(b)}},1E4)},yc=!1,zc=null,Hc=0,xc=null,Gc=0,vc=0,wc=0,Lc=0,Ic=[];function Sc(){zc=null;Hc++}var Kc={},Ac,Cc,Jc,Tc=!1,Uc=!1,Vc=[];
function xb(){function a(){Uc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}if(!Wc){Wc=!0;vb.push({canHandle:function(c){return!g.Od&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=new Blob([c],{type:Xc(d)});h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:Xc(d)}));var l=URL.createObjectURL(h),m=new Image;m.onload=()=>{m.complete||t(`Image ${d} could not be decoded`);
var r=document.createElement("canvas");r.width=m.width;r.height=m.height;r.getContext("2d").drawImage(m,0,0);URL.revokeObjectURL(l);e&&e(c)};m.onerror=()=>{n(`Image ${l} could not be decoded`);f&&f()};m.src=l}});vb.push({canHandle:function(c){return!g.Nd&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){h||(h=!0,e&&e(c))}var h=!1,l=URL.createObjectURL(new Blob([c],{type:Xc(d)})),m=new Audio;m.addEventListener("canplaythrough",()=>f(m),!1);m.onerror=function(){if(!h){n(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var r="",p=0,u=0,w=0;w<c.length;w++)for(p=p<<8|c[w],u+=8;6<=u;){var k=p>>u-6&63;u-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[k]}2==u?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&3)<<4],r+="=="):4==u&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(p&15)<<2],r+="=");m.src="data:audio/x-"+d.substr(-3)+";base64,"+r;f(m)}};m.src=l;Rc(()=>{f(m)})}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",
c=>{!Uc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Yc(a,b,c,d){if(b&&g.Cb&&a==g.canvas)return g.Cb;var e;if(b){var f={antialias:!1,alpha:!1,vc:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!=typeof Zc&&(e=$c(a,f)))var l=ad[e].Ib}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof O||t("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Cb=l,b&&(N=ad[e],g.Cb=O=N&&N.Ib),g.Rd=b,Vc.forEach(m=>m()),xb());return l}var bd=!1,cd=void 0,dd=void 0;
function ed(a,b){function c(){Tc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=fd,cd&&d.requestPointerLock(),Tc=!0,dd?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=B[SDL.screen>>2]|8388608),gd(g.canvas),hd()):gd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),dd?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=B[SDL.screen>>2]&
-8388609),gd(g.canvas),hd()):gd(d));if(g.onFullScreen)g.onFullScreen(Tc);if(g.onFullscreen)g.onFullscreen(Tc)}cd=a;dd=b;"undefined"==typeof cd&&(cd=!0);"undefined"==typeof dd&&(dd=!1);var d=g.canvas;bd||(bd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function fd(){if(!Tc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var jd=0;function Dc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jd)jd=b+1E3/60;else for(;b+2>=jd;)jd+=1E3/60;setTimeout(a,Math.max(jd-b,0))}}
function Xc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var kd=0,ld=0,md=0,nd=0;
function od(a){if(Uc)"mousemove"!=a.type&&"mozMovementX"in a?md=nd=0:(md=a.movementX||a.mozMovementX||a.webkitMovementX||0,nd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(kd=SDL.Kd+md,ld=SDL.Ld+nd):(kd+=md,ld+=nd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,md=e-kd,nd=a-ld,kd=e,ld=a)}}var pd=[];function hd(){var a=g.canvas;pd.forEach(b=>b(a.width,a.height))}function qd(a,b,c){gd(g.canvas,a,b);c||hd()}
function gd(a,b,c){b&&c?(a.sd=b,a.Vc=c):(b=a.sd,c=a.Vc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}dd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var wb={},Ec,Wc,rd=[],sd,Q=a=>{var b=rd[a];b||(a>=rd.length&&(rd.length=a+1),rd[a]=b=sd.get(a));return b},td={},vd=()=>{if(!ud){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in td)void 0===td[b]?delete a[b]:a[b]=td[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ud=c}return ud},ud,wd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");
b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,h)=>b.drawElementsInstancedANGLE(c,d,e,f,h))},xd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},yd=a=>{var b=a.getExtension("WEBGL_draw_buffers");
b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},zd=1,Ad=[],S=[],T=[],Bd=[],ad=[],Cd=[1,1,2,2,4,4,4,2,3,4,8];function Dd(a){Ed||=a}
var Fd=a=>{for(var b=zd++,c=a.length;c<b;c++)a[c]=null;return b},$c=(a,b)=>{a.ib||(a.ib=a.getContext,a.getContext=function(d,e){e=a.ib(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.vc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Gd(c,b):0},Gd=(a,b)=>{var c=Fd(ad),d={handle:c,attributes:b,version:b.vc,Ib:a};a.canvas&&(a.canvas.td=d);ad[c]=d;("undefined"==typeof b.Tc||b.Tc)&&Hd(d);d.wc=d.Ib.getParameter(34921);d.Jb=[];for(a=0;a<d.wc;a++)d.Jb[a]={enabled:!1,
Ub:!1,size:0,type:0,Ac:0,fc:0,lb:0,Lc:null};d.sb=[];d.Rb=[];d.sb.length=d.Rb.length=22;d.Bb=[];d.Gb=[];d.Bb.length=d.Gb.length=22;d.Ab=[];d.Ab.length=22;for(a=0;21>=a;++a){d.Ab[a]=null;d.sb[a]=d.Rb[a]=0;d.Bb[a]=[];d.Gb[a]=[];b=d.Bb[a];var e=d.Gb[a];b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},Hd=a=>{a||=N;if(!a.Xc){a.Xc=!0;var b=a.Ib;wd(b);xd(b);yd(b);b.Ed=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Jd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.pc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.pc)b.pc=b.getExtension("EXT_disjoint_timer_query");b.Md=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Zc={},Ed,N,Id,Jd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=O[c](),h=f&&Fd(d);f?(f.name=h,d[h]=f):Dd(1282);A[b+4*e>>2]=h}},Kd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ld=a=>{var b=O.Sc;if(b){var c=b.Hb[a];"number"==
typeof c&&(b.Hb[a]=c=O.getUniformLocation(b,b.Jc[a]+(0<c?`[${c}]`:"")));return c}Dd(1282)},Md=[];function Nd(a,b,c,d){this.id=a;this.y=this.x=0;this.Zb=!1;this.Ic=this.Hc=0;this.width=b;this.height=c;this.Gc=b;this.Fc=c;this.title=d;this.attributes=Od;this.buttons=0;this.keys=[];this.Wb=[];this.md=0;this.title=null;this.lc=this.tc=this.Xb=this.Cc=this.Lb=this.Vb=this.yc=this.Mc=this.Mb=this.Nc=0}
var U=null,Pd=null,V=null,Od=null,Qd={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},Rd=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;
case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;
case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;
case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;
case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}},Sd=()=>{var a=U,b=0;a.keys[340]&&
(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b},Td=a=>{U&&U.lc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||Q(U.lc)(U.id,a))},Ud=(a,b)=>{if(U){var c=Rd(a);if(-1!=c){var d=b&&U.keys[c];U.keys[c]=b;U.Wb[a]=b;U.tc&&(d&&(b=2),Q(U.tc)(U.id,c,a,b,Sd()))}}},Wd=()=>{Vd()},Xd=()=>{Vd()},Yd=a=>{Ud(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},Zd=a=>{Ud(a.keyCode,0)},ae=()=>{if(U)for(var a=0;a<U.Wb.length;++a)U.Wb[a]&&Ud(a,0)},be=a=>{U&&(od(a),a.target==
g.canvas&&U.Vb&&U.Vb&&Q(U.Vb)(U.id,kd,ld))},ce=a=>{U&&a.target==g.canvas&&U.Lb&&Q(U.Lb)(U.id,1)},de=a=>{U&&a.target==g.canvas&&U.Lb&&Q(U.Lb)(U.id,0)},ee=(a,b)=>{if(U&&(od(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){U.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else U.buttons&=~(1<<c);U.yc&&Q(U.yc)(U.id,c,b,Sd())}},fe=a=>{U&&ee(a,1)},ge=a=>{U&&ee(a,0)},he=a=>{switch(a.type){case "DOMMouseScroll":var b=a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=
a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);if(U&&U.Cc&&a.target==g.canvas){var c=b;b="mousewheel"==a.type?a.wheelDeltaX:a.deltaX;Q(U.Cc)(U.id,b,c);a.preventDefault()}},ie={},je=[],ke=null,Vd=()=>{if(Lc!==ke||!Lc){je=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?
navigator.webkitGetGamepads:[];ke=Lc;for(var a=0;a<je.length;++a){var b=je[a];if(b){ie[a]||(pa("glfw joystick connected:",a),ie[a]={id:uc(b.id),xd:b.buttons.length,wd:b.axes.length,buttons:tc(b.buttons.length),axes:tc(4*b.axes.length)});for(var c=ie[a],d=0;d<b.buttons.length;++d)v[c.buttons+d>>0]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)va[c.axes+4*d>>2]=b.axes[d]}else ie[a]&&(pa("glfw joystick disconnected",a),le(ie[a].id),le(ie[a].buttons),le(ie[a].axes),delete ie[a])}}},me=a=>{function b(l){var m=
"/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),r=new FileReader;r.onloadend=u=>{if(2!=r.readyState)++f,pa("failed to read dropped file: "+l.name+": "+r.error);else{var w=new Uint8Array(u.target.result);u={};u.flags=u.flags||577;var k=bc(m,u.flags,u.mode);if("string"==typeof w){var x=new Uint8Array(gb(w)+1);w=hb(w,x,0,x.length);fc(k,x,0,w,void 0,u.Rc)}else if(ArrayBuffer.isView(w))fc(k,w,0,w.byteLength,void 0,u.Rc);else throw Error("Unsupported data type");dc(k);if(++f===e){Q(U.Xb)(U.id,e,c);for(u=
0;u<d.length;++u)le(d[u]);le(c)}}};r.readAsArrayBuffer(l);var p=uc(m);d.push(p);B[c+4*h>>2]=p}if(U&&U.Xb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=tc(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;ic("/",".glfw_dropped_files");for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}},ne=a=>{if(U&&U.Xb)return a.preventDefault(),!1},oe=[31,29,31,30,31,30,31,31,30,31,30,31],pe=[31,28,31,30,31,30,31,31,30,31,30,31],qe=(a,b,c,
d)=>{function e(k,x,z){for(k="number"==typeof k?k.toString():k||"";k.length<x;)k=z[0]+k;return k}function f(k,x){return e(k,x,"0")}function h(k,x){function z(P){return 0>P?-1:0<P?1:0}var G;0===(G=z(k.getFullYear()-x.getFullYear()))&&0===(G=z(k.getMonth()-x.getMonth()))&&(G=z(k.getDate()-x.getDate()));return G}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),
0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var x=k.ub;for(k=new Date((new Date(k.vb+1900,0,1)).getTime());0<x;){var z=k.getMonth(),G=(qc(k.getFullYear())?oe:pe)[z];if(x>G-k.getDate())x-=G-k.getDate()+1,k.setDate(1),11>z?k.setMonth(z+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+x);break}}z=new Date(k.getFullYear()+1,0,4);x=l(new Date(k.getFullYear(),0,4));z=l(z);return 0>=h(x,k)?0>=h(z,k)?k.getFullYear()+
1:k.getFullYear():k.getFullYear()-1}var r=B[d+40>>2];d={pd:A[d>>2],od:A[d+4>>2],Sb:A[d+8>>2],hc:A[d+12>>2],Tb:A[d+16>>2],vb:A[d+20>>2],pb:A[d+24>>2],ub:A[d+28>>2],Qd:A[d+32>>2],nd:A[d+36>>2],qd:r?r?F(y,r):"":""};c=c?F(y,c):"";r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I",
"%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in r)c=c.replace(new RegExp(p,"g"),r[p]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");r={"%a":k=>u[k.pb].substring(0,3),"%A":k=>u[k.pb],"%b":k=>w[k.Tb].substring(0,3),"%B":k=>w[k.Tb],"%C":k=>f((k.vb+1900)/100|0,2),"%d":k=>f(k.hc,2),"%e":k=>e(k.hc,2," "),"%g":k=>
m(k).toString().substring(2),"%G":k=>m(k),"%H":k=>f(k.Sb,2),"%I":k=>{k=k.Sb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var x=0,z=0;z<=k.Tb-1;x+=(qc(k.vb+1900)?oe:pe)[z++]);return f(k.hc+x,3)},"%m":k=>f(k.Tb+1,2),"%M":k=>f(k.od,2),"%n":()=>"\n","%p":k=>0<=k.Sb&&12>k.Sb?"AM":"PM","%S":k=>f(k.pd,2),"%t":()=>"\t","%u":k=>k.pb||7,"%U":k=>f(Math.floor((k.ub+7-k.pb)/7),2),"%V":k=>{var x=Math.floor((k.ub+7-(k.pb+6)%7)/7);2>=(k.pb+371-k.ub-2)%7&&x++;if(x)53==x&&(z=(k.pb+371-k.ub)%7,4==z||3==z&&qc(k.vb)||
(x=1));else{x=52;var z=(k.pb+7-k.ub-1)%7;(4==z||5==z&&qc(k.vb%400-1))&&x++}return f(x,2)},"%w":k=>k.pb,"%W":k=>f(Math.floor((k.ub+7-(k.pb+6)%7)/7),2),"%y":k=>(k.vb+1900).toString().substring(2),"%Y":k=>k.vb+1900,"%z":k=>{k=k.nd;var x=0<=k;k=Math.abs(k)/60;return(x?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.qd,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(p in r)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),r[p](d)));c=c.replace(/\0\0/g,"%");p=ib(c,!1);if(p.length>b)return 0;v.set(p,
a);return p.length-1};function Nb(a,b,c,d){a||=this;this.parent=a;this.qb=a.qb;this.yb=null;this.id=Fb++;this.name=b;this.mode=c;this.fb={};this.hb={};this.rdev=d}Object.defineProperties(Nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},cd:{get:function(){return J(this.mode)}},bd:{get:function(){return 8192===(this.mode&61440)}}});
gc();Gb=Array(4096);Vb(I,"/");L("/tmp");L("/home");L("/home/web_user");(function(){L("/dev");lb(259,{read:()=>0,write:(d,e,f,h)=>h});Xb("/dev/null",259);kb(1280,nb);kb(1536,ob);Xb("/dev/tty",1280);Xb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=bb(a).byteLength);return a[--b]};kc("/dev","random",c);kc("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Vb({qb(){var b=rb(a,"fd",16895,73);b.fb={lookup(c,d){var e=Sb(+d);c={parent:null,qb:{xc:"fake"},fb:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=ic;g.FS_createDataFile=zb;g.FS_createPreloadedFile=Ab;g.FS_unlink=$b;g.FS_createLazyFile=mc;g.FS_createDevice=kc;g.requestFullscreen=ed;g.requestAnimationFrame=Dc;g.setCanvasSize=qd;g.pauseMainLoop=Sc;
g.resumeMainLoop=function(){Hc++;var a=vc,b=wc,c=xc;xc=null;Oc(c,0,!1,Gc,!0);Fc(a,b);zc()};g.getUserMedia=function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};g.createContext=Yc;for(var O,re=new Float32Array(288),se=0;288>se;++se)Md[se]=re.subarray(0,se+1);
var Ne={p:a=>{a=new Ta(a);a.Wc()||(a.Dc(!0),Ra--);a.Ec(!1);Qa.push(a);te(a.Eb);return a.dd()},s:()=>{W(0,0);var a=Qa.pop();ue(a.Eb);Sa=0},b:()=>Xa([]),m:a=>Xa([a]),H:(a,b,c,d)=>Xa([a,b,c,d]),na:()=>{var a=Qa.pop();a||t("no exception to throw");var b=a.Eb;a.Uc()||(Qa.push(a),a.Ec(!0),a.Dc(!1),Ra++);Sa=b;throw Sa;},a:(a,b,c)=>{(new Ta(a)).ed(b,c);Sa=a;Ra++;throw Sa;},d:a=>{Sa||=a;throw Sa;},la:function(a){try{a=a?F(y,a):"";var b=K(a,{Fb:!0});if(null===b.node)throw new H(44);if(!J(b.node.mode))throw new H(54);
var c=Mb(b.node,"x");if(c)throw new H(c);db=b.path;return 0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.kb}},F:function(a,b,c){oc=c;try{var d=Sb(a);switch(b){case 0:var e=pc();if(0>e)return-28;for(;Eb[e];)e++;return Tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=pc(),d.flags|=e,0;case 5:return e=pc(),ua[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return A[ve()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof M||
"ErrnoError"!==f.name)throw f;return-f.kb}},ea:function(a,b){try{if(0===b)return-28;var c=db,d=gb(c)+1;if(b<d)return-68;hb(c,y,a,b);return d}catch(e){if("undefined"==typeof M||"ErrnoError"!==e.name)throw e;return-e.kb}},ga:function(a,b,c){oc=c;try{var d=Sb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.rb.Zc){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=pc();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var f=
0;32>f;f++)v[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.rb.$c)for(e=pc(),b=[],f=0;32>f;f++)b.push(v[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=pc();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=pc();if(!d.hb.Yc)throw new H(59);return d.hb.Yc(d,b,e);case 21523:if(!d.tty)return-59;d.tty.rb.ad&&(f=[24,80],e=pc(),ua[e>>1]=f[0],ua[e+2>>1]=f[1]);return 0;case 21524:return d.tty?
0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof M||"ErrnoError"!==h.name)throw h;return-h.kb}},aa:function(a,b,c){try{return b=b?F(y,b):"",b=nc(a,b),b=E(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),L(b,c),0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.kb}},ha:function(a,b,c,d){oc=d;try{b=b?F(y,b):"";b=nc(a,b);var e=d?pc():0;return bc(b,c,e).fd}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.kb}},$:function(a,
b,c,d){try{b=b?F(y,b):"";b=nc(a,b);if(0>=d)return-28;var e=Ib(b),f=Math.min(d,gb(e)),h=v[c+f];hb(e,y,c,d+1);v[c+f]=h;return f}catch(l){if("undefined"==typeof M||"ErrnoError"!==l.name)throw l;return-l.kb}},Z:function(a){try{return a=a?F(y,a):"",Zb(a),0}catch(b){if("undefined"==typeof M||"ErrnoError"!==b.name)throw b;return-b.kb}},Y:function(a,b){try{a=a?F(y,a):"";a:{try{var c=K(a,{Fb:!0}).node;if(!c)throw new H(44);if(!c.fb.nb)throw new H(63);var d=c.fb.nb(c)}catch(m){if(m&&m.node&&E(a)!==E(Jb(m.node))){var e=
-54;break a}throw m;}A[b>>2]=d.dev;A[b+4>>2]=d.mode;B[b+8>>2]=d.nlink;A[b+12>>2]=d.uid;A[b+16>>2]=d.gid;A[b+20>>2]=d.rdev;D=[d.size>>>0,(C=d.size,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+24>>2]=D[0];A[b+28>>2]=D[1];A[b+32>>2]=4096;A[b+36>>2]=d.blocks;var f=d.atime.getTime(),h=d.mtime.getTime(),l=d.ctime.getTime();D=[Math.floor(f/1E3)>>>0,(C=Math.floor(f/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>
0:0)];A[b+40>>2]=D[0];A[b+44>>2]=D[1];B[b+48>>2]=f%1E3*1E3;D=[Math.floor(h/1E3)>>>0,(C=Math.floor(h/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+56>>2]=D[0];A[b+60>>2]=D[1];B[b+64>>2]=h%1E3*1E3;D=[Math.floor(l/1E3)>>>0,(C=Math.floor(l/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+72>>2]=D[0];A[b+76>>2]=D[1];B[b+80>>2]=l%1E3*1E3;D=[d.ino>>>0,(C=d.ino,1<=+Math.abs(C)?0<C?+Math.floor(C/
4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+88>>2]=D[0];A[b+92>>2]=D[1];e=0}return e}catch(m){if("undefined"==typeof M||"ErrnoError"!==m.name)throw m;return-m.kb}},_:function(a,b,c){try{return b=b?F(y,b):"",b=nc(a,b),0===c?$b(b):512===c?Zb(b):t("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.kb}},ia:()=>1,Q:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));A[c>>2]=a.getSeconds();
A[c+4>>2]=a.getMinutes();A[c+8>>2]=a.getHours();A[c+12>>2]=a.getDate();A[c+16>>2]=a.getMonth();A[c+20>>2]=a.getFullYear()-1900;A[c+24>>2]=a.getDay();A[c+28>>2]=(qc(a.getFullYear())?rc:sc)[a.getMonth()]+a.getDate()-1|0;A[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();A[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},X:(a,b,c)=>{function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?
m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),h=new Date(e,6,1);e=f.getTimezoneOffset();var l=h.getTimezoneOffset();B[a>>2]=60*Math.max(e,l);A[b>>2]=Number(e!=l);a=d(f);b=d(h);a=uc(a);b=uc(b);l<e?(B[c>>2]=a,B[c+4>>2]=b):(B[c>>2]=b,B[c+4>>2]=a)},r:()=>{t("")},B:()=>{Sc();xc=null},ja:()=>Date.now(),x:Bc,ka:(a,b,c)=>y.copyWithin(a,b,b+c),W:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=
(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ra.buffer.byteLength+65535)/65536;try{ra.grow(e);wa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},D:(a,b,c)=>{a=Q(a);Oc(a,b,c)},ca:(a,b)=>{var c=0;vd().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=f;for(f=0;f<d.length;++f)v[e++>>0]=d.charCodeAt(f);v[e>>0]=0;c+=d.length+1});return 0},da:(a,b)=>{var c=vd();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},o:Qc,G:function(a){try{var b=Sb(a);dc(b);return 0}catch(c){if("undefined"==
typeof M||"ErrnoError"!==c.name)throw c;return c.kb}},ba:function(a,b){try{var c=Sb(a);v[b>>0]=c.tty?2:J(c.mode)?3:40960===(c.mode&61440)?7:4;ua[b+2>>1]=0;D=[0,(C=0,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+8>>2]=D[0];A[b+12>>2]=D[1];D=[0,(C=0,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+16>>2]=D[0];A[b+20>>2]=D[1];return 0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;
return d.kb}},fa:function(a,b,c,d){try{a:{var e=Sb(a);a=b;for(var f,h=b=0;h<c;h++){var l=B[a>>2],m=B[a+4>>2];a+=8;var r=e,p=l,u=m,w=f,k=v;if(0>u||0>w)throw new H(28);if(null===r.fd)throw new H(8);if(1===(r.flags&2097155))throw new H(8);if(J(r.node.mode))throw new H(31);if(!r.hb.read)throw new H(28);var x="undefined"!=typeof w;if(!x)w=r.position;else if(!r.seekable)throw new H(70);var z=r.hb.read(r,k,p,u,w);x||(r.position+=z);var G=z;if(0>G){var P=-1;break a}b+=G;if(G<m)break;"undefined"!==typeof f&&
(f+=G)}P=b}B[d>>2]=P;return 0}catch(ba){if("undefined"==typeof M||"ErrnoError"!==ba.name)throw ba;return ba.kb}},R:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Sb(a);ec(f,b,d);D=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[e>>2]=D[0];A[e+4>>2]=D[1];f.$b&&0===b&&0===d&&(f.$b=null);return 0}catch(h){if("undefined"==typeof M||"ErrnoError"!==h.name)throw h;return h.kb}},
E:function(a,b,c,d){try{a:{var e=Sb(a);a=b;for(var f,h=b=0;h<c;h++){var l=B[a>>2],m=B[a+4>>2];a+=8;var r=fc(e,v,l,m,f);if(0>r){var p=-1;break a}b+=r;"undefined"!==typeof f&&(f+=r)}p=b}B[d>>2]=p;return 0}catch(u){if("undefined"==typeof M||"ErrnoError"!==u.name)throw u;return u.kb}},K:(a,b)=>{O.attachShader(S[a],T[b])},w:(a,b)=>{34962==a?O.Kb=b:34963==a&&(O.Db=b);35051==a?O.nc=b:35052==a&&(O.oc=b);O.bindBuffer(a,Ad[b])},pa:a=>{O.bindVertexArray(Bd[a]);a=O.getParameter(34965);O.Db=a?a.name|0:0},Ia:function(a,
b){O.blendFunc(a,b)},v:(a,b,c,d)=>{2<=N.version?c&&b?O.bufferData(a,y,d,c,b):O.bufferData(a,b,d):O.bufferData(a,c?y.subarray(c,c+b):b,d)},Oa:function(a){O.clear(a)},V:function(a,b,c,d){O.clearColor(a,b,c,d)},Aa:a=>{O.compileShader(T[a])},ya:()=>{var a=Fd(S),b=O.createProgram();b.name=a;b.Pb=b.Nb=b.Ob=0;b.ic=1;S[a]=b;return a},Ca:a=>{var b=Fd(T);T[b]=O.createShader(a);return b},Na:(a,b)=>{for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=Ad[d];e&&(O.deleteBuffer(e),e.name=0,Ad[d]=null,d==O.Kb&&(O.Kb=0),d==
O.Db&&(O.Db=0),d==O.nc&&(O.nc=0),d==O.oc&&(O.oc=0))}},ua:a=>{if(a){var b=S[a];b?(O.deleteProgram(b),b.name=0,S[a]=null):Dd(1281)}},A:a=>{if(a){var b=T[a];b?(O.deleteShader(b),T[a]=null):Dd(1281)}},Ha:function(a){O.depthFunc(a)},L:(a,b,c,d)=>{if(!O.Db){var e=1*Cd[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var h=N.Ab[f];h?f=h:(h=O.getParameter(34965),N.Ab[f]=O.createBuffer(),O.bindBuffer(34963,N.Ab[f]),O.bufferData(34963,1<<f,35048),O.bindBuffer(34963,h),f=N.Ab[f]);O.bindBuffer(34963,f);O.bufferSubData(34963,
0,y.subarray(d,d+e));d=0}Id=!1;for(e=0;e<N.wc;++e)if(f=N.Jb[e],f.Ub&&f.enabled){Id=!0;h=f.fc;h=0<h?b*h:f.size*Cd[f.type-5120]*b;var l=32-Math.clz32(0===h?0:h-1);var m=N.Bb[l],r=N.sb[l];N.sb[l]=N.sb[l]+1&63;var p=m[r];p?l=p:(p=O.getParameter(34964),m[r]=O.createBuffer(),O.bindBuffer(34962,m[r]),O.bufferData(34962,1<<l,35048),O.bindBuffer(34962,p),l=m[r]);O.bindBuffer(34962,l);O.bufferSubData(34962,0,y.subarray(f.lb,f.lb+h));f.Lc.call(O,e,f.size,f.type,f.Ac,f.fc,0)}O.drawElements(a,b,c,d);Id&&O.bindBuffer(34962,
Ad[O.Kb]);O.Db||O.bindBuffer(34963,null)},C:function(a){O.enable(a)},z:a=>{N.Jb[a].enabled=!0;O.enableVertexAttribArray(a)},O:(a,b)=>{Jd(a,b,"createBuffer",Ad)},qa:function(a,b){Jd(a,b,"createVertexArray",Bd)},va:(a,b,c,d)=>{a=O.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?hb(a,y,d,b):0;c&&(A[c>>2]=b)},J:(a,b,c)=>{if(c)if(a>=zd)Dd(1281);else if(a=S[a],35716==b)a=O.getProgramInfoLog(a),null===a&&(a="(unknown error)"),A[c>>2]=a.length+1;else if(35719==b){if(!a.Pb)for(b=0;b<O.getProgramParameter(a,
35718);++b)a.Pb=Math.max(a.Pb,O.getActiveUniform(a,b).name.length+1);A[c>>2]=a.Pb}else if(35722==b){if(!a.Nb)for(b=0;b<O.getProgramParameter(a,35721);++b)a.Nb=Math.max(a.Nb,O.getActiveAttrib(a,b).name.length+1);A[c>>2]=a.Nb}else if(35381==b){if(!a.Ob)for(b=0;b<O.getProgramParameter(a,35382);++b)a.Ob=Math.max(a.Ob,O.getActiveUniformBlockName(a,b).length+1);A[c>>2]=a.Ob}else A[c>>2]=O.getProgramParameter(a,b);else Dd(1281)},za:(a,b,c,d)=>{a=O.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=
0<b&&d?hb(a,y,d,b):0;c&&(A[c>>2]=b)},M:(a,b,c)=>{c?35716==b?(a=O.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=O.getShaderSource(T[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=O.getShaderParameter(T[a],b):Dd(1281)},sa:(a,b)=>{b=b?F(y,b):"";if(a=S[a]){var c=a,d=c.Hb,e=c.Kc,f;if(!d)for(c.Hb=d={},c.Jc={},f=0;f<O.getProgramParameter(c,35718);++f){var h=O.getActiveUniform(c,f);var l=h.name;h=h.size;var m=Kd(l);m=0<m?l.slice(0,m):l;var r=c.ic;c.ic+=h;e[m]=[h,r];for(l=
0;l<h;++l)d[r]=l,c.Jc[r++]=m}c=a.Hb;d=0;e=b;f=Kd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Kc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||O.getUniformLocation(a,b)))return d}else Dd(1281);return-1},xa:a=>{a=S[a];O.linkProgram(a);a.Hb=0;a.Kc={}},Ba:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var h=d?A[d+4*f>>2]:-1,l=A[c+4*f>>2];h=l?F(y,l,0>h?void 0:h):"";e+=h}O.shaderSource(T[a],e)},ra:(a,b,c,d)=>{if(2<=N.version)b&&O.uniformMatrix4fv(Ld(a),!!c,va,d>>2,16*b);else{if(18>=b){var e=Md[16*b-1],f=va;
d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=va.subarray(d>>2,d+64*b>>2);O.uniformMatrix4fv(Ld(a),!!c,e)}},ta:a=>{a=S[a];O.useProgram(a);O.Sc=a},wa:a=>{O.validateProgram(S[a])},y:(a,b,c,d,e,f)=>{var h=N.Jb[a];O.Kb?(h.Ub=!1,O.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=
b,h.type=c,h.Ac=d,h.fc=e,h.lb=f,h.Ub=!0,h.Lc=function(l,m,r,p,u,w){this.vertexAttribPointer(l,m,r,p,u,w)})},P:function(a,b,c,d){O.viewport(a,b,c,d)},La:(a,b,c,d)=>{var e;for(e=0;e<V.length&&null!==V[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?ed():qd(a,b);for(e=0;e<V.length&&null==V[e];e++);d=0<Od[139265];e==V.length&&(d?g.Cb=Yc(g.canvas,!0,!0,{antialias:1<Od[135181],depth:0<Od[135173],stencil:0<Od[135174],alpha:0<Od[135172]}):
xb());!g.Cb&&d?f=0:(a=new Nd(f,a,b,c),f-1==V.length?V.push(a):V[f-1]=a,U=a,f=a.id)}return f},Ea:(a,b,c)=>{var d=0,e=0;if(a=0>=a||!V?null:V[a-1])d=a.width,e=a.height;b&&(A[b>>2]=d);c&&(A[c>>2]=e)},Ma:()=>{if(V)return 1;Bc();Od=Qd;V=[];U=null;Pd="number"==typeof devicePixelRatio&&devicePixelRatio||1;window.addEventListener("gamepadconnected",Wd,!0);window.addEventListener("gamepaddisconnected",Xd,!0);window.addEventListener("keydown",Yd,!0);window.addEventListener("keypress",Td,!0);window.addEventListener("keyup",
Zd,!0);window.addEventListener("blur",ae,!0);(function b(){window.matchMedia("(resolution: "+window.devicePixelRatio+"dppx)").addEventListener("change",b,{once:!0});Pd="number"==typeof devicePixelRatio&&devicePixelRatio||1;U&&U.Mc&&Q(U.Mc)(U.id,Pd,Pd)})();g.canvas.addEventListener("touchmove",be,!0);g.canvas.addEventListener("touchstart",fe,!0);g.canvas.addEventListener("touchcancel",ge,!0);g.canvas.addEventListener("touchend",ge,!0);g.canvas.addEventListener("mousemove",be,!0);g.canvas.addEventListener("mousedown",
fe,!0);g.canvas.addEventListener("mouseup",ge,!0);g.canvas.addEventListener("wheel",he,!0);g.canvas.addEventListener("mousewheel",he,!0);g.canvas.addEventListener("mouseenter",ce,!0);g.canvas.addEventListener("mouseleave",de,!0);g.canvas.addEventListener("drop",me,!0);g.canvas.addEventListener("dragover",ne,!0);pd.push((b,c)=>{if(U){var d=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(U.Hc=U.x,U.Ic=U.y,U.Gc=U.width,U.Fc=U.height,U.x=U.y=0,U.width=
screen.width,U.height=screen.height,U.Zb=!0):1==U.Zb?(U.x=U.Hc,U.y=U.Ic,U.width=U.Gc,U.height=U.Fc,U.Zb=!1):U.width!=b||U.height!=c?(U.width=b,U.height=c):d=!1;d&&(qd(U.width,U.height,!0),U&&U.Nc&&Q(U.Nc)(U.id,U.width,U.height),U&&U.Mb&&Q(U.Mb)(U.id,U.width,U.height))}});return 1},Ka:()=>{},Da:()=>{},Ja:(a,b)=>{a=0>=a||!V?null:V[a-1];if(!a)return null;var c=a.Mb;a.Mb=b;return c},Fa:()=>{},N:(a,b)=>{Od[a]=b},Ga:a=>(a=0>=a||!V?null:V[a-1])?a.md:0,e:we,I:xe,f:ye,c:ze,n:Ae,t:Be,ma:Ce,oa:De,T:Ee,l:Fe,
h:Ge,g:He,i:Ie,j:Je,u:Ke,k:Le,S:Me,q:a=>a,U:(a,b,c,d)=>qe(a,b,c,d)},X=function(){function a(c){X=c.exports;ra=X.Pa;wa();sd=X.Sa;ya.unshift(X.Qa);Ga("wasm-instantiate");return X}var b={a:Ne};Fa("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Na(b,function(c){a(c.instance)});return{}}(),Oe=g._main=(a,b)=>(Oe=g._main=X.Ra)(a,b),ve=()=>(ve=X.Ta)(),le=a=>(le=X.Ua)(a),tc=a=>(tc=X.Va)(a),W=(a,b)=>(W=
X.Wa)(a,b),Va=a=>(Va=X.Xa)(a),Y=()=>(Y=X.Ya)(),Z=a=>(Z=X.Za)(a),Pe=a=>(Pe=X._a)(a),ue=a=>(ue=X.$a)(a),te=a=>(te=X.ab)(a),Wa=(a,b,c)=>(Wa=X.bb)(a,b,c),Ua=a=>(Ua=X.cb)(a),Qe=g.dynCall_iij=(a,b,c,d)=>(Qe=g.dynCall_iij=X.db)(a,b,c,d),Re=g.dynCall_vij=(a,b,c,d)=>(Re=g.dynCall_vij=X.eb)(a,b,c,d);function Ie(a,b,c,d){var e=Y();try{Q(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function ye(a,b,c){var d=Y();try{return Q(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}
function ze(a,b,c,d){var e=Y();try{return Q(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function we(a,b){var c=Y();try{return Q(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function He(a,b,c){var d=Y();try{Q(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Ge(a,b){var c=Y();try{Q(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Ke(a,b,c,d,e,f){var h=Y();try{Q(a)(b,c,d,e,f)}catch(l){Z(h);if(l!==l+0)throw l;W(1,0)}}
function Be(a,b,c,d,e,f){var h=Y();try{return Q(a)(b,c,d,e,f)}catch(l){Z(h);if(l!==l+0)throw l;W(1,0)}}function Le(a,b,c,d,e,f,h){var l=Y();try{Q(a)(b,c,d,e,f,h)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function Fe(a){var b=Y();try{Q(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function Je(a,b,c,d,e){var f=Y();try{Q(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}function Ae(a,b,c,d,e){var f=Y();try{return Q(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}
function De(a,b,c,d,e,f,h,l,m,r){var p=Y();try{return Q(a)(b,c,d,e,f,h,l,m,r)}catch(u){Z(p);if(u!==u+0)throw u;W(1,0)}}function xe(a,b,c){var d=Y();try{return Q(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Ce(a,b,c,d,e,f,h,l,m){var r=Y();try{return Q(a)(b,c,d,e,f,h,l,m)}catch(p){Z(r);if(p!==p+0)throw p;W(1,0)}}function Ee(a,b,c,d){var e=Y();try{return Qe(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function Me(a,b,c,d){var e=Y();try{Re(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}g.addRunDependency=Fa;g.removeRunDependency=Ga;g.FS_createPath=ic;g.FS_createLazyFile=mc;g.FS_createDevice=kc;g.FS_createPreloadedFile=Ab;g.FS_createDataFile=zb;g.FS_unlink=$b;var Se;Ea=function Te(){Se||Ue();Se||(Ea=Te)};
function Ve(a=[]){var b=Oe;a.unshift(da);var c=a.length,d=Pe(4*(c+1)),e=d;a.forEach(h=>{var l=B,m=e>>2,r=gb(h)+1,p=Pe(r);hb(h,y,p,r);l[m]=p;e+=4});B[e>>2]=0;try{var f=b(c,d);Qc(f,!0)}catch(h){Nc(h)}}
function Ue(){var a=ca;function b(){if(!Se&&(Se=!0,g.calledRun=!0,!sa)){g.noFSInit||hc||(hc=!0,gc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?kc("/dev","stdin",g.stdin):Yb("/dev/tty","/dev/stdin"),g.stdout?kc("/dev","stdout",null,g.stdout):Yb("/dev/tty","/dev/stdout"),g.stderr?kc("/dev","stderr",null,g.stderr):Yb("/dev/tty1","/dev/stderr"),bc("/dev/stdin",0),bc("/dev/stdout",1),bc("/dev/stderr",1));Hb=!1;Oa(ya);Oa(za);if(g.onRuntimeInitialized)g.onRuntimeInitialized();We&&Ve(a);
if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Aa.unshift(c)}Oa(Aa)}}if(!(0<Ca)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ba();Oa(xa);0<Ca||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var We=!0;
g.noInitialRun&&(We=!1);Ue();
